# frozen_string_literal: true

require "delegate"
require "pg_query"
require "tempfile"
require "quaack/enclave/arena_runner"
require "quaack/enclave/table_name"

# Steps 9a, 9b, and 9e against a real arena database: open a transaction
# with statement_timeout, load a fixture, run queries, and always roll back.
RSpec.describe Quaack::Enclave::ArenaRunner do
  let(:arena) { racetrack_and_arena.arena }
  let(:conn) { arena.connection }
  let(:runner) { described_class.new(conn) }

  # Planted in fixture values and queries. It must never show up in an error.
  let(:sentinel) { "SENTINEL-7f3a9c" }

  let(:parents) { Quaack::Enclave::TableName.new(schema: "Fixture Space", name: "Parent Rows") }
  let(:children) { Quaack::Enclave::TableName.new(schema: "Fixture Space", name: "children") }
  let(:counters) { Quaack::Enclave::TableName.new(schema: "Fixture Space", name: "counters") }

  # A mixed-case schema and table with spaces, so the INSERTs must quote.
  before do
    conn.exec(<<~SQL)
      CREATE SCHEMA "Fixture Space";
      CREATE TABLE "Fixture Space"."Parent Rows" (
        id integer PRIMARY KEY,
        "Code" text NOT NULL UNIQUE,
        qty integer CHECK (qty > 0),
        note text
      );
      CREATE TABLE "Fixture Space".children (
        id integer PRIMARY KEY,
        parent_code text NOT NULL REFERENCES "Fixture Space"."Parent Rows" ("Code"),
        price numeric
      );
      CREATE TABLE "Fixture Space".counters (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        label text NOT NULL DEFAULT 'none'
      );
    SQL
  end

  def row(table, values)
    described_class::FixtureRow.new(table: table, columns: values.keys, values: values.values)
  end

  def parent(id, code, qty: 1, note: nil)
    row(parents, { "id" => id.to_s, "Code" => code, "qty" => qty&.to_s, "note" => note })
  end

  def child(id, code, price: nil) = row(children, { "id" => id.to_s, "parent_code" => code, "price" => price })

  # Counted from a fresh connection, so it sees only what was committed.
  def persisted_rows
    other = arena.connect
    other.exec(<<~SQL).getvalue(0, 0).to_i
      SELECT (SELECT count(*) FROM "Fixture Space"."Parent Rows")
           + (SELECT count(*) FROM "Fixture Space".children)
           + (SELECT count(*) FROM "Fixture Space".counters)
    SQL
  ensure
    other&.close
  end

  # PQTRANS_IDLE is 0 and PQTRANS_INTRANS is 2, from libpq.
  def expect_nothing_persisted
    expect(conn.transaction_status).to eq(0)
    expect(persisted_rows).to eq(0)
  end

  let(:timeout_sql) { "SELECT current_setting('statement_timeout')" }

  def session_timeout = conn.exec("SHOW statement_timeout").getvalue(0, 0)

  def run_error(runner = self.runner, rows = [], **, &block)
    block ||= proc {}
    runner.with_fixture(rows, **, &block)
    raise "expected ArenaRunner::Error"
  rescue described_class::Error => e
    e
  end

  describe "loading and querying" do
    it "loads the rows in order and returns each query's columns, type OIDs, and text rows" do
      rows = [parent(1, "a", note: "first"), parent(2, "b", qty: nil), child(10, "a", price: "1.50"), child(11, "b")]

      result = runner.with_fixture(rows) do |tx|
        tx.query('SELECT p.id, p."Code", p.qty, c.price FROM "Fixture Space"."Parent Rows" p ' \
                 'JOIN "Fixture Space".children c ON c.parent_code = p."Code" ORDER BY p.id')
      end

      expect(result).to eq(described_class::Result.new(
                             columns: %w[id Code qty price], types: [23, 25, 23, 1700],
                             rows: [["1", "a", "1", "1.50"], ["2", "b", nil, nil]]
                           ))
      expect_nothing_persisted
    end

    it "runs several queries against one loaded fixture and returns the block's value" do
      counts = runner.with_fixture([parent(1, "a"), parent(2, "b")]) do |tx|
        sql = 'SELECT count(*) FROM "Fixture Space"."Parent Rows" WHERE %s'
        [tx.query(format(sql, "qty = 1")), tx.query(format(sql, "TRUE")), tx.query(format(sql, "id = 2"))]
          .map { |r| r.rows.dig(0, 0) }
      end

      expect(counts).to eq(%w[2 2 1])
      expect_nothing_persisted
    end

    it "runs raw INSERT statements after the rows, each on its own" do
      inserts = ['INSERT INTO "Fixture Space".children VALUES (20, \'a\', 2)',
                 'INSERT INTO "Fixture Space".children VALUES (21, \'a\', 3)']

      rows = runner.with_fixture([parent(1, "a")], inserts: inserts) do |tx|
        tx.query('SELECT id, price FROM "Fixture Space".children ORDER BY id').rows
      end

      expect(rows).to eq([%w[20 2], %w[21 3]])
      expect_nothing_persisted
    end

    it "inserts a row with no columns as DEFAULT VALUES" do
      rows = runner.with_fixture([row(counters, {})]) do |tx|
        tx.query('SELECT id, label FROM "Fixture Space".counters').rows
      end

      expect(rows).to eq([%w[1 none]])
      expect_nothing_persisted
    end

    it "moves an identity sequence past the fixture's explicit values, so an insert that leaves it out fits" do
      inserts = ['INSERT INTO "Fixture Space".counters (label) VALUES (\'x\')']
      rows = runner.with_fixture([row(counters, { "id" => "1" }), row(counters, { "id" => "5" })], inserts:) do |tx|
        tx.query('SELECT id FROM "Fixture Space".counters ORDER BY id').rows
      end

      expect(rows).to eq([%w[1], %w[5], %w[6]])
    end

    it "keeps the sequence within its bounds when the fixture's value is below its minimum" do
      inserts = ['INSERT INTO "Fixture Space".counters (label) VALUES (\'x\')']
      rows = runner.with_fixture([row(counters, { "id" => "-5", "label" => "a" })], inserts:) do |tx|
        tx.query('SELECT id FROM "Fixture Space".counters ORDER BY id').rows
      end

      expect(rows).to eq([%w[-5], %w[2]])
    end

    it "retries with rebuilt rows after a rollback, on the same connection" do
      sql = 'SELECT "Code" FROM "Fixture Space"."Parent Rows"'

      codes = %w[a z].map { |code| runner.with_fixture([parent(1, code)]) { |tx| tx.query(sql).rows } }

      expect(codes).to eq([[["a"]], [["z"]]])
      expect_nothing_persisted
    end
  end

  describe "statement_timeout" do
    it "defaults to 10 seconds, set only for the transaction" do
      inside = runner.with_fixture { |tx| tx.query(timeout_sql).rows }

      expect(inside).to eq([["10s"]])
      expect(session_timeout).to eq("0")
    end

    it "takes the timeout in milliseconds" do
      runner = described_class.new(conn, statement_timeout_ms: 250)

      inside = runner.with_fixture { |tx| tx.query(timeout_sql).rows }

      expect(inside).to eq([["250ms"]])
    end

    it "refuses a timeout that isn't a positive Integer" do
      [0, -5, 1.5, "100", nil].each do |bad|
        expect { described_class.new(conn, statement_timeout_ms: bad) }
          .to raise_error(ArgumentError, "statement_timeout_ms must be a positive Integer"), bad.inspect
      end
    end

    it "turns a timed-out query into a statement_timeout error and rolls back" do
      short = described_class.new(conn, statement_timeout_ms: 100)

      error = run_error(short, [parent(1, "a")]) { |tx| tx.query("SELECT pg_sleep(5)") }

      expect([error.rule, error.sqlstate, error.step, error.index]).to eq([:statement_timeout, "57014", :query, 0])
      expect_nothing_persisted
    end
  end

  describe "index scans" do
    let(:scan_settings) do
      "SELECT current_setting('enable_indexscan'), current_setting('enable_indexonlyscan'), " \
        "current_setting('enable_bitmapscan')"
    end

    def session_scans = conn.exec(scan_settings).values

    it "leaves index scans on by default" do
      expect(runner.with_fixture { |tx| tx.query(scan_settings).rows }).to eq([%w[on on on]])
    end

    it "turns index, index-only, and bitmap scans off for the transaction only, when asked" do
      inside = runner.with_fixture(index_scans: false) { |tx| tx.query(scan_settings).rows }

      expect(inside).to eq([%w[off off off]])
      expect(session_scans).to eq([%w[on on on]])
    end

    it "refuses an index_scans that isn't true or false" do
      expect { runner.with_fixture(index_scans: "off") }
        .to raise_error(ArgumentError, "index_scans must be true or false")
    end
  end

  describe "always rolling back" do
    it "rolls back after a query error, naming the query by its position" do
      error = run_error(runner, [parent(1, "a")]) do |tx|
        tx.query("SELECT 1")
        tx.query('SELECT 1 / (id - id) FROM "Fixture Space"."Parent Rows"')
      end

      expect([error.rule, error.sqlstate, error.step, error.index]).to eq([:query_failed, "22012", :query, 1])
      expect(error.message).to eq("a query failed in the arena transaction")
      expect_nothing_persisted
    end

    it "rolls back after a fixture row fails to load, naming the row by its position" do
      error = run_error(runner, [parent(1, "a"), child(10, "a"), parent(2, "a")]) { raise "not reached" }

      expect([error.rule, error.sqlstate, error.step, error.index]).to eq([:fixture_load_failed, "23505", :load, 2])
      expect_nothing_persisted
    end

    it "rolls back after a raw INSERT statement fails" do
      inserts = ['INSERT INTO "Fixture Space".children VALUES (20, \'a\', 2)',
                 'INSERT INTO "Fixture Space".children VALUES (21, \'missing\', 3)']

      error = run_error(runner, [parent(1, "a")], inserts: inserts) { raise "not reached" }

      expect([error.rule, error.sqlstate, error.step, error.index]).to eq([:insert_failed, "23503", :insert, 1])
      expect_nothing_persisted
    end

    it "rolls back and lets the block's own exception through untouched" do
      failure = Class.new(StandardError)

      expect do
        runner.with_fixture([parent(1, "a")]) do |tx|
          tx.query("SELECT 1")
          raise failure, "from the block"
        end
      end.to raise_error(failure, "from the block")
      expect_nothing_persisted
    end

    # The statement check refuses COMMIT and the like before they run, so
    # this reaches past it to the backstop that checks the transaction is
    # still open after every statement.
    it "reports a statement that ended the transaction, as a backstop to the statement check" do
      # Inside a caller's rescue, so a missing cause: nil would show.
      error = begin
        raise sentinel
      rescue StandardError
        run_error { runner.__send__(:statement, "COMMIT", [], step: :query, rule: :query_failed, index: 3) }
      end

      expect([error.rule, error.step, error.index, error.cause]).to eq([:transaction_ended, :query, 3, nil])
      expect(conn.transaction_status).to eq(0)
      # SET LOCAL ends with the transaction, even one that was committed.
      expect(session_timeout).to eq("0")
    end

    it "refuses a string of several statements in the backstop too" do
      error = run_error do
        runner.__send__(:statement, 'SELECT 1; INSERT INTO "Fixture Space".counters DEFAULT VALUES', [],
                        step: :query, rule: :query_failed, index: 0)
      end

      expect([error.rule, error.sqlstate]).to eq([:query_failed, "42601"])
      expect_nothing_persisted
    end

    it "keeps the block's own exception when the connection dies and the rollback fails too" do
      failure = Class.new(StandardError)

      expect do
        runner.with_fixture([parent(1, "a")]) do
          terminate(conn)
          raise failure, "from the block"
        end
      end.to raise_error(failure, "from the block")
      expect(persisted_rows).to eq(0)
    end

    it "keeps the query's own error when the connection dies and the rollback fails too" do
      error = run_error(runner, [parent(1, "a")]) do |tx|
        terminate(conn)
        tx.query("SELECT 1")
      end

      expect([error.rule, error.step, error.index, error.cause]).to eq([:query_failed, :query, 0, nil])
      expect(persisted_rows).to eq(0)
    end

    it "refuses a query through the transaction after the block has returned" do
      kept = nil
      runner.with_fixture { |tx| kept = tx }

      expect { kept.query('INSERT INTO "Fixture Space".counters DEFAULT VALUES') }
        .to raise_error(described_class::Error) { |e| expect(e.rule).to eq(:transaction_closed) }
      expect_nothing_persisted
    end

    it "turns a rollback that fails into its own error" do
      other = arena.connect

      error = run_error(described_class.new(other)) { other.close }

      expect([error.rule, error.sqlstate, error.step, error.cause]).to eq([:rollback_failed, nil, :rollback, nil])
    end
  end

  # Ends conn's backend from another session, the way a crash or an
  # operator would.
  def terminate(victim)
    pid = victim.backend_pid
    killer = arena.connect
    # Waits up to five seconds for the backend to be gone.
    killer.exec_params("SELECT pg_terminate_backend($1::int, 5000)", [pid])
  ensure
    killer&.close
  end

  describe "a connection that can't start a transaction" do
    it "reports a closed connection as unusable" do
      other = arena.connect
      other.close

      error = run_error(described_class.new(other))

      expect([error.rule, error.step, error.sqlstate,
              error.cause]).to eq([:connection_unusable, :transaction, nil, nil])
    end

    # PQTRANS_UNKNOWN is 4: libpq has seen the connection go bad.
    it "reports a dead connection as unusable" do
      other = arena.connect
      terminate(other)
      begin
        other.exec("SELECT 1")
      rescue StandardError
        nil
      end
      expect(other.transaction_status).to eq(4)

      error = run_error(described_class.new(other))

      expect([error.rule, error.step]).to eq(%i[connection_unusable transaction])
    ensure
      other&.close
    end

    # PQTRANS_ACTIVE is 1: a query was sent and its result not yet read.
    it "reports a connection busy with a query as unusable, and leaves the query alone" do
      conn.send_query("SELECT 42")
      expect(conn.transaction_status).to eq(1)

      error = run_error

      expect([error.rule, error.step]).to eq(%i[connection_unusable transaction])
      expect(conn.get_result.getvalue(0, 0)).to eq("42")
      conn.get_result
    end
  end

  describe "a connection already inside a transaction" do
    it "refuses inside a caller's rescue without taking the caller's exception as its cause" do
      conn.exec("BEGIN")

      error = begin
        raise sentinel
      rescue StandardError
        run_error
      end

      expect([error.rule, error.cause]).to eq([:already_in_transaction, nil])
      conn.exec("ROLLBACK")
    end

    it "refuses a connection in a failed transaction too" do
      conn.exec("BEGIN")
      begin
        conn.exec("SELECT 1 / 0")
      rescue StandardError
        nil
      end
      expect(conn.transaction_status).to eq(3)

      expect(run_error.rule).to eq(:already_in_transaction)
      conn.exec("ROLLBACK")
    end

    it "refuses, and leaves that transaction alone" do
      conn.exec("BEGIN")
      conn.exec('INSERT INTO "Fixture Space".counters DEFAULT VALUES')
      yielded = false

      error = run_error { yielded = true }

      expect([error.rule, yielded]).to eq([:already_in_transaction, false])
      expect(conn.transaction_status).to eq(2)
      expect(conn.exec('SELECT count(*) FROM "Fixture Space".counters').getvalue(0, 0)).to eq("1")
      conn.exec("ROLLBACK")
    end
  end

  describe "fixture rows" do
    it "refuses a row whose columns and values don't line up, without naming the values" do
      expect { described_class::FixtureRow.new(table: parents, columns: %w[id note], values: [sentinel]) }
        .to raise_error(ArgumentError, "a fixture row needs one value per column")
    end

    it "refuses values that aren't Strings or nil, without naming them" do
      expect { described_class::FixtureRow.new(table: parents, columns: ["id"], values: [7]) }
        .to raise_error(ArgumentError, "fixture row values must be Strings or nil")
    end

    it "refuses a table that isn't a TableName, and column names that aren't non-empty Strings" do
      expect { described_class::FixtureRow.new(table: "public.t", columns: [], values: []) }
        .to raise_error(ArgumentError, "a fixture row's table must be a TableName")
      [[""], [:id]].each do |columns|
        expect { described_class::FixtureRow.new(table: parents, columns: columns, values: [nil]) }
          .to raise_error(ArgumentError, "fixture row columns must be non-empty Strings"), columns.inspect
      end
    end
  end

  # Postgres puts real values in its errors: a unique violation's DETAIL has
  # the key, and a check violation's has the whole row. None of it may reach
  # the runner's errors.
  describe "errors never carry values" do
    # Everything an error shows, down its cause chain.
    def texts_of(error)
      texts = []
      while error
        texts.push(error.message, error.full_message, error.detailed_message, error.inspect)
        %i[rule sqlstate step index].each { |field| texts << error.public_send(field).to_s if error.respond_to?(field) }
        error = error.cause
      end
      texts
    end

    # The same failure straight through the connection, to prove Postgres
    # really does put the sentinel in its error, so texts_of would find it.
    def raw_error(sql, params = [])
      other = arena.connect
      other.exec("BEGIN")
      other.exec_params(sql, params)
      raise "expected a database error"
    rescue StandardError => e
      e
    ensure
      other&.close
    end

    def expect_no_sentinel(error)
      expect(error).to be_a(described_class::Error)
      expect(error.cause).to be_nil
      expect(texts_of(error).grep(/#{sentinel}/)).to be_empty
    end

    def expect_sentinel_in_raw(sql, params = [])
      expect(texts_of(raw_error(sql, params)).grep(/#{sentinel}/)).not_to be_empty
    end

    it "keeps a colliding unique key out of the error" do
      error = run_error(runner, [parent(1, sentinel), parent(2, sentinel)])

      expect([error.rule, error.sqlstate]).to eq([:fixture_load_failed, "23505"])
      expect_no_sentinel(error)
      expect_sentinel_in_raw(<<~SQL, [sentinel])
        INSERT INTO "Fixture Space"."Parent Rows" (id, "Code") VALUES (1, $1), (2, $1)
      SQL
    end

    it "keeps a CHECK-violating row out of the error" do
      error = run_error(runner, [parent(1, "a", qty: -1, note: sentinel)])

      expect([error.rule, error.sqlstate]).to eq([:fixture_load_failed, "23514"])
      expect_no_sentinel(error)
      expect_sentinel_in_raw(<<~SQL, [sentinel])
        INSERT INTO "Fixture Space"."Parent Rows" (id, "Code", qty, note) VALUES (1, 'a', -1, $1)
      SQL
    end

    it "keeps a NOT NULL-violating row out of the error" do
      error = run_error(runner, [parent(1, nil, note: sentinel)])

      expect([error.rule, error.sqlstate]).to eq([:fixture_load_failed, "23502"])
      expect_no_sentinel(error)
      expect_sentinel_in_raw(<<~SQL, [sentinel])
        INSERT INTO "Fixture Space"."Parent Rows" (id, "Code", note) VALUES (1, NULL, $1)
      SQL
    end

    it "keeps a missing foreign key out of the error" do
      error = run_error(runner, [child(10, sentinel)])

      expect([error.rule, error.sqlstate]).to eq([:fixture_load_failed, "23503"])
      expect_no_sentinel(error)
      expect_sentinel_in_raw('INSERT INTO "Fixture Space".children (id, parent_code) VALUES (10, $1)', [sentinel])
    end

    it "keeps a raw INSERT statement's values out of the error" do
      sql = %(INSERT INTO "Fixture Space".children (id, parent_code) VALUES (10, '#{sentinel}'))

      error = run_error(runner, [], inserts: [sql])

      expect([error.rule, error.sqlstate]).to eq([:insert_failed, "23503"])
      expect_no_sentinel(error)
      expect_sentinel_in_raw(sql)
    end

    it "keeps a failing query's values and column names out of the error" do
      queries = [%(SELECT '#{sentinel}' AS "#{sentinel}", 1 / 0 AS "#{sentinel}-2"),
                 %(SELECT '#{sentinel}'::integer AS "#{sentinel}")]

      queries.each do |sql|
        error = run_error { |tx| tx.query(sql) }

        expect(error.rule).to eq(:query_failed)
        expect_no_sentinel(error)
      end
      expect_sentinel_in_raw(queries.last)
    end
  end

  # Only an INSERT may load and only a SELECT may query, so a COMMIT, or a
  # COMMIT AND CHAIN that would open a new transaction without the timeout,
  # never runs.
  describe "the statement check" do
    let(:refused) do
      ["COMMIT", "END", "ROLLBACK", "COMMIT AND CHAIN", "SAVEPOINT s", "PREPARE TRANSACTION 'quaack'",
       "SET statement_timeout = 0", "SHOW statement_timeout",
       'SELECT 1; INSERT INTO "Fixture Space".counters DEFAULT VALUES', "SELECT 1; SELECT 2",
       'INSERT INTO "Fixture Space".counters DEFAULT VALUES; INSERT INTO "Fixture Space".counters DEFAULT VALUES',
       'INSERT INTO "Fixture Space".counters DEFAULT VALUES; COMMIT', ""]
    end

    it "refuses anything but a single SELECT as a query, before it runs, and the transaction goes on" do
      refused.each do |sql|
        seen = runner.with_fixture([parent(1, "a")]) do |tx|
          error = begin
            tx.query(sql)
            nil
          rescue described_class::Error => e
            e
          end
          [error&.rule, error&.step, error&.index, conn.transaction_status, tx.query(timeout_sql).rows]
        end

        expect(seen).to eq([:statement_not_allowed, :query, 0, 2, [["10s"]]]), sql
        expect_nothing_persisted
        expect(session_timeout).to eq("0")
      end
    end

    it "refuses an INSERT as a query" do
      error = run_error { |tx| tx.query('INSERT INTO "Fixture Space".counters DEFAULT VALUES') }

      expect(error.rule).to eq(:statement_not_allowed)
      expect_nothing_persisted
    end

    it "refuses anything but a single INSERT among the inserts, before the transaction starts" do
      (refused + ["SELECT 1"]).each do |sql|
        yielded = false
        inserts = ['INSERT INTO "Fixture Space".counters DEFAULT VALUES', sql]

        error = run_error(runner, [parent(1, "a")], inserts: inserts) { yielded = true }

        expect([error.rule, error.step, error.index, yielded]).to eq([:statement_not_allowed, :insert, 1, false]), sql
        expect_nothing_persisted
        expect(session_timeout).to eq("0")
      end
    end

    it "accepts an INSERT with a WITH clause and a SELECT with one" do
      inserts = ['WITH v(id) AS (VALUES (5)) INSERT INTO "Fixture Space".counters (id) SELECT id FROM v']

      rows = runner.with_fixture([], inserts: inserts) do |tx|
        tx.query('WITH c AS (SELECT id FROM "Fixture Space".counters) SELECT id FROM c').rows
      end

      expect(rows).to eq([["5"]])
      expect_nothing_persisted
    end

    it "reports SQL it can't parse without repeating it" do
      sql = "SELECT '#{sentinel}' '#{sentinel}'"

      query_error = run_error { |tx| tx.query(sql) }
      insert_error = run_error(runner, [], inserts: [sql])

      [[query_error, :query], [insert_error, :insert]].each do |error, step|
        expect([error.rule, error.step, error.index, error.cause]).to eq([:statement_unparsable, step, 0, nil])
        expect([error.message, error.full_message, error.inspect].grep(/#{sentinel}/)).to be_empty
      end
      expect { PgQuery.parse(sql) }.to raise_error(PgQuery::ParseError, /#{sentinel}/)
    end

    it "refuses a query and an insert that aren't Strings" do
      expect { runner.with_fixture { |tx| tx.query(:select) } }
        .to raise_error(ArgumentError, "a query must be a String")
      [[:insert], "INSERT"].each do |inserts|
        expect { runner.with_fixture([], inserts: inserts) { raise "not reached" } }
          .to raise_error(ArgumentError, "inserts must be an Array of Strings"), inserts.inspect
      end
      expect_nothing_persisted
    end

    it "refuses inside a caller's rescue without taking the caller's exception as its cause" do
      errors = runner.with_fixture do |tx|
        [proc { tx.query("COMMIT") }, proc { tx.query("SELECT FROM WHERE") }].map do |bad|
          raise sentinel
        rescue StandardError
          begin
            bad.call
          rescue described_class::Error => e
            e
          end
        end
      end

      expect(errors.map { |e| [e.rule, e.cause] }).to eq([[:statement_not_allowed, nil], [:statement_unparsable, nil]])
    end
  end

  describe "the fixture itself" do
    it "refuses rows that aren't FixtureRows before the transaction starts" do
      [[:junk], [parent(1, "a"), "row"], :junk, {}].each do |rows|
        yielded = false

        expect { runner.with_fixture(rows) { yielded = true } }
          .to raise_error(ArgumentError, "rows must be an Array of FixtureRows"), rows.inspect
        expect(yielded).to be(false)
        expect_nothing_persisted
      end
    end
  end

  describe "fixture row copies" do
    it "keeps its own frozen copies of the columns and values" do
      columns = [+"id", +"Code"]
      values = [+"1", nil]

      fixture_row = described_class::FixtureRow.new(table: parents, columns: columns, values: values)
      columns.first << "x"
      columns << "qty"
      values.first << "2"
      values << "3"

      expect([fixture_row.columns, fixture_row.values]).to eq([%w[id Code], ["1", nil]])
      expect([fixture_row.columns, fixture_row.values, fixture_row.columns.first, fixture_row.values.first])
        .to all(be_frozen)
    end

    it "refuses columns or values that aren't Arrays" do
      expect { described_class::FixtureRow.new(table: parents, columns: "id", values: ["1"]) }
        .to raise_error(ArgumentError, "fixture row columns must be non-empty Strings")
      [nil, "1", { "id" => "1" }].each do |values|
        expect { described_class::FixtureRow.new(table: parents, columns: ["id"], values: values) }
          .to raise_error(ArgumentError, "a fixture row needs one value per column"), values.inspect
      end
    end
  end

  describe "the transaction handle" do
    it "refuses after the block inside a caller's rescue without taking its exception as the cause" do
      kept = nil
      runner.with_fixture { |tx| kept = tx }

      error = begin
        raise sentinel
      rescue StandardError
        begin
          kept.query("SELECT 1")
        rescue described_class::Error => e
          e
        end
      end

      expect([error.rule, error.cause]).to eq([:transaction_closed, nil])
    end
  end

  # Postgres notices go to stderr through libpq's default receiver, and the
  # enclave's stderr reaches the laptop. A notice can carry a real value, as
  # shout's does here from a table CHECK, a domain CHECK, and a query.
  describe "notices" do
    let(:noisy) { Quaack::Enclave::TableName.new(schema: "Fixture Space", name: "noisy") }

    before do
      conn.exec(<<~SQL)
        CREATE FUNCTION "Fixture Space".shout(v text) RETURNS boolean IMMUTABLE LANGUAGE plpgsql AS $$
          BEGIN RAISE NOTICE 'VAL=%', v; RETURN true; END
        $$;
        CREATE DOMAIN "Fixture Space".loud AS text CHECK ("Fixture Space".shout(VALUE));
        CREATE TABLE "Fixture Space".noisy (id integer PRIMARY KEY, a text CHECK ("Fixture Space".shout(a)),
                                            b "Fixture Space".loud);
      SQL
    end

    def noisy_run
      rows = [row(noisy, { "id" => "1", "a" => "#{sentinel}-check", "b" => "#{sentinel}-domain" })]
      runner.with_fixture(rows) do |tx|
        tx.query(%(SELECT "Fixture Space".shout('#{sentinel}-query')))
        tx.query('SELECT a, b FROM "Fixture Space".noisy').rows
      end
    end

    def shout(word) = conn.exec(%(SELECT "Fixture Space".shout('#{word}')))

    # Everything written to fd 2, where libpq's default receiver writes.
    def fd2
      saved = $stderr.dup
      Tempfile.create("arena-stderr") do |file|
        $stderr.reopen(file)
        yield
        $stderr.flush
        file.rewind
        return file.read
      ensure
        $stderr.reopen(saved)
      end
    end

    it "drops them while it runs, and puts the default receiver back" do
      loaded = nil
      written = fd2 do
        shout("before")
        loaded = noisy_run
        shout("after")
      end

      expect(loaded).to eq([["#{sentinel}-check", "#{sentinel}-domain"]])
      expect(written).to include("VAL=before").and include("VAL=after")
      expect(written).not_to include(sentinel)
      expect(conn.set_notice_receiver { nil }).to be_nil
    end

    it "drops them while it runs, and puts a caller's receiver back" do
      heard = []
      conn.set_notice_receiver { |result| heard << result.error_message }

      shout("before")
      noisy_run
      shout("after")

      expect(heard.join).to include("VAL=before").and include("VAL=after")
      expect(heard.grep(/#{sentinel}/)).to be_empty
      expect(heard.size).to eq(2)
    end

    it "puts the receiver back after a failure too" do
      heard = []
      conn.set_notice_receiver { |result| heard << result.error_message }

      run_error { |tx| tx.query("SELECT 1 / 0") }
      shout("after")

      expect(heard.join).to include("VAL=after")
    end
  end

  # A connection that fails one chosen call with an error that isn't
  # Postgres's and that carries the sentinel, the way a driver-level fault
  # might. It fakes only the edge. Everything else goes to the real
  # connection.
  describe "a connection call that fails with some other error" do
    let(:flaky_class) do
      Class.new(SimpleDelegator) do
        def initialize(conn, method, call, message)
          super(conn)
          @fail = [method, call]
          @message = message
          @calls = Hash.new(0)
        end

        %i[exec exec_params transaction_status set_notice_receiver].each do |name|
          define_method(name) do |*args, &block|
            @calls[name] += 1
            raise IOError, @message if @fail == [name, @calls[name]]

            __getobj__.public_send(name, *args, &block)
          end
        end
      end
    end

    def flaky_error(method, call)
      flaky = flaky_class.new(conn, method, call, sentinel)
      run_error(described_class.new(flaky), [parent(1, "a"), parent(2, "b")])
    end

    it "reports each by its phase, with no SQLSTATE and nothing from the error" do
      cases = {
        [:transaction_status, 1] => [:connection_unusable, :transaction, nil],
        [:set_notice_receiver, 1] => [:connection_unusable, :transaction, nil],
        [:exec, 1] => [:begin_failed, :begin, nil],
        [:exec, 2] => [:begin_failed, :begin, nil],
        [:exec_params, 4] => [:fixture_load_failed, :load, 1], # after two setvals (id, qty)
        [:transaction_status, 4] => [:fixture_load_failed, :load, 0]
      }

      cases.each do |(method, call), expected|
        error = flaky_error(method, call)

        seen = [error.rule, error.step, error.index, error.sqlstate, error.cause]
        expect(seen).to eq([*expected, nil, nil]), [method, call].inspect
        expect([error.message, error.full_message, error.inspect].grep(/#{sentinel}/)).to be_empty
        expect_nothing_persisted
      end
    end
  end
end
