# frozen_string_literal: true

require "delegate"
require "pg_query"
require "tempfile"
require "quaack/enclave/arena_runner"
require "quaack/enclave/table_name"
require_relative "support/server_clock"

# fixture-open, fixture-load, and fixture-rollback against a real arena database: open a transaction
# with statement_timeout, load a fixture, run queries, and always roll back.
RSpec.describe Quaack::Enclave::ArenaRunner do
  let(:arena) { racetrack_and_arena.arena }
  let(:conn) { arena.connection }
  let(:runner) { described_class.new(conn) }

  # Planted in fixture values and queries. It must never show up in an error.
  let(:sentinel) { "SENTINEL-7f3a9c" }

  let(:parents) { Quaack::Enclave::TableName.new(schema: "Fixture Space", name: "Parent Rows") }
  let(:children) { Quaack::Enclave::TableName.new(schema: "Fixture Space", name: "children") }
  let(:counters) { Quaack::Enclave::TableName.new(schema: "Fixture Space", name: "counters") }

  # A mixed-case schema and table with spaces, so the INSERTs must quote.
  before do
    conn.exec(<<~SQL)
      CREATE SCHEMA "Fixture Space";
      CREATE TABLE "Fixture Space"."Parent Rows" (
        id integer PRIMARY KEY,
        "Code" text NOT NULL UNIQUE,
        qty integer CHECK (qty > 0),
        note text
      );
      CREATE TABLE "Fixture Space".children (
        id integer PRIMARY KEY,
        parent_code text NOT NULL REFERENCES "Fixture Space"."Parent Rows" ("Code"),
        price numeric
      );
      CREATE TABLE "Fixture Space".counters (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        label text NOT NULL DEFAULT 'none'
      );
    SQL
  end

  def row(table, values)
    described_class::FixtureRow.new(table: table, columns: values.keys, values: values.values)
  end

  def parent(id, code, qty: 1, note: nil)
    row(parents, { "id" => id.to_s, "Code" => code, "qty" => qty&.to_s, "note" => note })
  end

  def child(id, code, price: nil) = row(children, { "id" => id.to_s, "parent_code" => code, "price" => price })

  # Counted from a fresh connection, so it sees only what was committed.
  def persisted_rows
    other = arena.connect
    other.exec(<<~SQL).getvalue(0, 0).to_i
      SELECT (SELECT count(*) FROM "Fixture Space"."Parent Rows")
           + (SELECT count(*) FROM "Fixture Space".children)
           + (SELECT count(*) FROM "Fixture Space".counters)
    SQL
  ensure
    other&.close
  end

  # PQTRANS_IDLE is 0 and PQTRANS_INTRANS is 2, from libpq.
  def expect_nothing_persisted
    expect(conn.transaction_status).to eq(0)
    expect(persisted_rows).to eq(0)
  end

  let(:timeout_sql) { "SELECT current_setting('statement_timeout')" }

  def session_timeout = conn.exec("SHOW statement_timeout").getvalue(0, 0)

  def run_error(runner = self.runner, rows = [], **, &block)
    block ||= proc {}
    runner.with_fixture(rows, **, &block)
    raise "expected ArenaRunner::Error"
  rescue described_class::Error => e
    e
  end

  describe "loading and querying" do
    it "counts each fixture it loads, one that fails included, for the burndown's fixture loads" do
      expect(runner.loads).to eq(0)
      runner.with_fixture([parent(1, "a")]) { |tx| tx.query("SELECT 1") }
      runner.with_fixture { nil }
      expect { runner.with_fixture([parent(1, "a"), parent(2, "a")]) { nil } }.to raise_error(described_class::Error)

      expect(runner.loads).to eq(3)
    end

    it "loads the rows in order and returns each query's columns, type OIDs, and text rows" do
      rows = [parent(1, "a", note: "first"), parent(2, "b", qty: nil), child(10, "a", price: "1.50"), child(11, "b")]

      result = runner.with_fixture(rows) do |tx|
        tx.query('SELECT p.id, p."Code", p.qty, c.price FROM "Fixture Space"."Parent Rows" p ' \
                 'JOIN "Fixture Space".children c ON c.parent_code = p."Code" ORDER BY p.id')
      end

      expect(result).to eq(described_class::Result.new(
                             columns: %w[id Code qty price], types: [23, 25, 23, 1700],
                             rows: [["1", "a", "1", "1.50"], ["2", "b", nil, nil]]
                           ))
      expect_nothing_persisted
    end

    it "runs several queries against one loaded fixture and returns the block's value" do
      counts = runner.with_fixture([parent(1, "a"), parent(2, "b")]) do |tx|
        sql = 'SELECT count(*) FROM "Fixture Space"."Parent Rows" WHERE %s'
        [tx.query(format(sql, "qty = 1")), tx.query(format(sql, "TRUE")), tx.query(format(sql, "id = 2"))]
          .map { |r| r.rows.dig(0, 0) }
      end

      expect(counts).to eq(%w[2 2 1])
      expect_nothing_persisted
    end

    it "runs raw INSERT statements after the rows, each on its own" do
      inserts = ['INSERT INTO "Fixture Space".children VALUES (20, \'a\', 2)',
                 'INSERT INTO "Fixture Space".children VALUES (21, \'a\', 3)']

      rows = runner.with_fixture([parent(1, "a")], inserts: inserts) do |tx|
        tx.query('SELECT id, price FROM "Fixture Space".children ORDER BY id').rows
      end

      expect(rows).to eq([%w[20 2], %w[21 3]])
      expect_nothing_persisted
    end

    it "runs a deferred insert's UPDATEs after every insert, on just the rows it inserted" do
      conn.exec(<<~SQL)
        CREATE TABLE "Fixture Space".parts (id integer, note text) PARTITION BY RANGE (id);
        CREATE TABLE "Fixture Space".parts_low PARTITION OF "Fixture Space".parts FOR VALUES FROM (0) TO (10);
        CREATE TABLE "Fixture Space".parts_high PARTITION OF "Fixture Space".parts FOR VALUES FROM (10) TO (100);
      SQL
      deferred = described_class::DeferredInsert.new(
        sql: 'INSERT INTO "Fixture Space".parts VALUES (11, NULL)', updates: [{ "note" => "later" }]
      )
      inserts = ['INSERT INTO "Fixture Space".parts VALUES (1, NULL)', deferred,
                 'INSERT INTO "Fixture Space".parts VALUES (12, NULL)']

      rows = runner.with_fixture([], inserts:) do |tx|
        tx.query('SELECT id, note FROM "Fixture Space".parts ORDER BY id').rows
      end

      # Rows 1 and 11 share a ctid in different partitions, so only tableoid tells them apart.
      expect(rows).to eq([["1", nil], %w[11 later], ["12", nil]])
      expect_nothing_persisted
    end

    it "refuses a deferred insert whose updates don't match the rows it inserts" do
      deferred = described_class::DeferredInsert.new(
        sql: 'INSERT INTO "Fixture Space".counters (label) VALUES (\'a\'), (\'b\')', updates: [{ "label" => "c" }]
      )

      error = run_error(inserts: [deferred])

      expect([error.rule, error.step]).to eq(%i[insert_failed insert])
      expect_nothing_persisted
    end

    it "inserts a row with no columns as DEFAULT VALUES" do
      rows = runner.with_fixture([row(counters, {})]) do |tx|
        tx.query('SELECT id, label FROM "Fixture Space".counters').rows
      end

      expect(rows).to eq([%w[1 none]])
      expect_nothing_persisted
    end

    it "moves an identity sequence past the fixture's explicit values, so an insert that leaves it out fits" do
      inserts = ['INSERT INTO "Fixture Space".counters (label) VALUES (\'x\')']
      rows = runner.with_fixture([row(counters, { "id" => "1" }), row(counters, { "id" => "5" })], inserts:) do |tx|
        tx.query('SELECT id FROM "Fixture Space".counters ORDER BY id').rows
      end

      expect(rows).to eq([%w[1], %w[5], %w[6]])
    end

    it "keeps the sequence within its bounds when the fixture's value is below its minimum" do
      inserts = ['INSERT INTO "Fixture Space".counters (label) VALUES (\'x\')']
      rows = runner.with_fixture([row(counters, { "id" => "-5", "label" => "a" })], inserts:) do |tx|
        tx.query('SELECT id FROM "Fixture Space".counters ORDER BY id').rows
      end

      expect(rows).to eq([%w[-5], %w[2]])
    end

    it "retries with rebuilt rows after a rollback, on the same connection" do
      sql = 'SELECT "Code" FROM "Fixture Space"."Parent Rows"'

      codes = %w[a z].map { |code| runner.with_fixture([parent(1, code)]) { |tx| tx.query(sql).rows } }

      expect(codes).to eq([[["a"]], [["z"]]])
      expect_nothing_persisted
    end
  end

  describe "statement_timeout" do
    it "defaults to 10 seconds, set only for the transaction" do
      inside = runner.with_fixture { |tx| tx.query(timeout_sql).rows }

      expect(inside).to eq([["10s"]])
      expect(session_timeout).to eq("0")
    end

    it "takes the timeout in milliseconds" do
      runner = described_class.new(conn, statement_timeout_ms: 250)

      inside = runner.with_fixture { |tx| tx.query(timeout_sql).rows }

      expect(inside).to eq([["250ms"]])
    end

    it "refuses a timeout that isn't a positive Integer" do
      [0, -5, 1.5, "100", nil].each do |bad|
        expect { described_class.new(conn, statement_timeout_ms: bad) }
          .to raise_error(ArgumentError, "statement_timeout_ms must be a positive Integer"), bad.inspect
      end
    end

    it "turns a timed-out query into a statement_timeout error and rolls back" do
      short = described_class.new(conn, statement_timeout_ms: 100)

      error = run_error(short, [parent(1, "a")]) { |tx| tx.query("SELECT pg_sleep(5)") }

      expect([error.rule, error.sqlstate, error.step, error.index]).to eq([:statement_timeout, "57014", :query, 0])
      expect_nothing_persisted
    end

    it "turns a timed-out query into a statement_timeout error, even if the enclave's clock runs slower" do
      short = described_class.new(conn, statement_timeout_ms: 500)
      slow_enclave_clock

      error = run_error(short, [parent(1, "a")]) { |tx| tx.query("SELECT pg_sleep(5)") }

      expect([error.rule, error.sqlstate, error.step, error.index]).to eq([:statement_timeout, "57014", :query, 0])
      expect_nothing_persisted
    end

    it "turns a timed-out insert into a statement_timeout error, even if the enclave's clock runs slower" do
      short = described_class.new(conn, statement_timeout_ms: 500)
      slow_enclave_clock

      error = run_error(short, [], inserts: ['INSERT INTO "Fixture Space".counters (label) SELECT pg_sleep(5)::text'])

      expect([error.rule, error.sqlstate, error.step, error.index]).to eq([:statement_timeout, "57014", :insert, 0])
      expect_nothing_persisted
    end

    # A cancel shares the timeout's SQLSTATE, 57014, and its message depends
    # on lc_messages, so the runner tells them apart by time, as
    # RunDiscipline does: one that comes before the timeout could have
    # fired isn't the timeout.
    it "turns a cancel that isn't the timeout into a statement_canceled error and rolls back" do
      error = run_error(runner, [parent(1, "a")]) do |tx|
        tx.query("SELECT 1")
        tx.query("SELECT pg_cancel_backend(pg_backend_pid()), pg_sleep(5)")
      end

      expect([error.rule, error.sqlstate, error.step, error.index]).to eq([:statement_canceled, "57014", :query, 1])
      expect(error.message).to eq("a statement in the arena transaction was canceled")
      expect_nothing_persisted
    end

    # Telling the cancel apart rolls the transaction back, so a block that
    # catches the error and goes on would otherwise run its next query in
    # autocommit, without statement_timeout, and keep what it wrote. The
    # refusal must come before anything is sent: a read-only query in
    # autocommit leaves the transaction status as it was, so only a count of
    # what went to the server shows it wasn't run.
    describe "after a cancel has rolled the transaction back" do
      let(:sending_class) do
        Class.new(SimpleDelegator) do
          def initialize(conn)
            super
            @sends = []
          end

          def mark! = @mark = @sends.size

          def since_mark = @sends.drop(@mark)

          %i[exec exec_params send_query send_query_params pipeline_sync].each do |name|
            define_method(name) do |*args, &block|
              @sends << name
              __getobj__.public_send(name, *args, &block)
            end
          end
        end
      end

      def query_error(transaction, sql)
        transaction.query(sql)
        nil
      rescue described_class::Error => e
        [e.rule, e.step, e.index, e.sqlstate, e.cause]
      end

      # Each statement's error, or nil, and what was sent after the cancel,
      # up to the closing ROLLBACK.
      def after_cancel(statements)
        sending = sending_class.new(conn)
        described_class.new(sending).with_fixture([parent(1, "a")]) do |tx|
          canceled = query_error(tx, "SELECT pg_cancel_backend(pg_backend_pid()), pg_sleep(5)")
          sending.mark!
          [[canceled, *statements.map { query_error(tx, it) }], sending.since_mark]
        end
      end

      it "refuses a write before sending it, so nothing it writes persists" do
        write = 'WITH d AS (INSERT INTO "Fixture Space".counters DEFAULT VALUES RETURNING id) SELECT count(*) FROM d'

        errors, sends = after_cancel([write])

        expect(errors).to eq([[:statement_canceled, :query, 0, "57014", nil],
                              [:transaction_ended, :query, 1, nil, nil]])
        expect(sends).to eq([])
        expect_nothing_persisted
      end

      it "refuses a read-only query before sending it too" do
        errors, sends = after_cancel(["SELECT 1", "SELECT 2"])

        expect(errors).to eq([[:statement_canceled, :query, 0, "57014", nil],
                              [:transaction_ended, :query, 1, nil, nil], [:transaction_ended, :query, 2, nil, nil]])
        expect(sends).to eq([])
      end

      # Cancel.rule rolls back its own transaction even when the clock read
      # in it fails. This plants a read that fails on the server, so the
      # transaction it ran in is aborted, and only that ROLLBACK leaves the
      # connection idle, so the next statement is refused, not sent to fail
      # with 25P02.
      it "refuses the next statement even when the clock read after the cancel fails" do
        failing_read = Class.new(SimpleDelegator) do
          def exec(sql, *, &)
            sql = "SELECT 1/0" if sql.strip == Quaack::Enclave::ServerClock::NOW_SQL
            __getobj__.exec(sql, *, &)
          end
        end.new(conn)

        errors, status = described_class.new(failing_read).with_fixture([parent(1, "a")]) do |tx|
          canceled = query_error(tx, "SELECT pg_cancel_backend(pg_backend_pid()), pg_sleep(5)")
          [[canceled, query_error(tx, "SELECT 1")], conn.transaction_status]
        end

        expect(errors).to eq([[:statement_canceled, :query, 0, "57014", nil],
                              [:transaction_ended, :query, 1, nil, nil]])
        expect(status).to eq(0)
      end
    end

    # The time is measured from the start of each statement, not of the
    # transaction or the runner: ScenarioTests reuses one runner across
    # scenarios, so a cancel after the timeout's worth of earlier statements
    # must still read as a cancel. Each sleep is well under the timeout, and
    # together they're well over it.
    it "times each statement from its own start, so earlier statements don't turn a cancel into a timeout" do
      short = described_class.new(conn, statement_timeout_ms: 2000)

      error = run_error(short, [parent(1, "a")]) do |tx|
        tx.query("SELECT pg_sleep(1.3)")
        tx.query("SELECT pg_sleep(1.3)")
        tx.query("SELECT pg_cancel_backend(pg_backend_pid()), pg_sleep(5)")
      end

      expect([error.rule, error.sqlstate, error.step, error.index]).to eq([:statement_canceled, "57014", :query, 2])
      expect_nothing_persisted
    end

    # The timeout is armed for each statement only, after the clock is read,
    # so a clock read that's slow, as on a loaded server, isn't canceled by
    # it and still dates the statement. A clock_timestamp() earlier on the
    # search_path than pg_catalog's plants a read slower than the timeout.
    describe "a clock read slower than the timeout" do
      before do
        conn.exec(<<~SQL)
          CREATE SCHEMA slow_clock;
          CREATE FUNCTION slow_clock.clock_timestamp() RETURNS timestamptz LANGUAGE sql
            AS 'SELECT pg_catalog.clock_timestamp() FROM pg_catalog.pg_sleep(0.3)';
          SET search_path = slow_clock, pg_catalog, public;
        SQL
      end

      it "is slower than the timeout on its own" do
        conn.transaction do
          conn.exec("SET LOCAL statement_timeout = 100")
          expect { conn.exec(Quaack::Enclave::ServerClock::NOW_SQL) }
            .to raise_error(PG::QueryCanceled) { expect(it.result.error_field(67)).to eq("57014") }
        end
      end

      it "doesn't keep a timed-out statement from reading as statement_timeout" do
        error = run_error(described_class.new(conn, statement_timeout_ms: 100)) { |tx| tx.query("SELECT pg_sleep(5)") }

        expect([error.rule, error.sqlstate, error.step, error.index]).to eq([:statement_timeout, "57014", :query, 0])
        expect_nothing_persisted
      end
    end

    # After a cancel, Cancel.rule reads the clock once it has rolled back,
    # when the session's own statement_timeout is back in force. A nonzero
    # one, from the server, the database, the role, or a SET, mustn't cancel
    # that read and turn a timeout into statement_canceled, nor stay changed
    # afterwards. The slow clock read is planted as above.
    describe "a nonzero session default" do
      before do
        conn.exec(<<~SQL)
          CREATE SCHEMA slow_clock;
          CREATE FUNCTION slow_clock.clock_timestamp() RETURNS timestamptz LANGUAGE sql
            AS 'SELECT pg_catalog.clock_timestamp() FROM pg_catalog.pg_sleep(0.3)';
        SQL
      end

      def timed_out_on(connection)
        connection.exec("SET search_path = slow_clock, pg_catalog, public")
        runner = described_class.new(connection, statement_timeout_ms: 100)
        error = run_error(runner) { |tx| tx.query("SELECT pg_sleep(5)") }
        [error.rule, error.sqlstate, error.step, error.index, connection.transaction_status]
      end

      def setting_on(connection) = connection.exec("SHOW statement_timeout").getvalue(0, 0)

      it "doesn't keep a timed-out statement from reading as statement_timeout under a database default" do
        conn.exec("ALTER DATABASE #{conn.quote_ident(arena.name)} SET statement_timeout = '50ms'")
        defaulted = arena.connect
        expect(setting_on(defaulted)).to eq("50ms")

        expect(timed_out_on(defaulted)).to eq([:statement_timeout, "57014", :query, 0, 0])
        expect(setting_on(defaulted)).to eq("50ms")
      ensure
        defaulted&.close
      end

      it "doesn't keep a timed-out statement from reading as statement_timeout under a session SET" do
        conn.exec("SET statement_timeout = 50")

        expect(timed_out_on(conn)).to eq([:statement_timeout, "57014", :query, 0, 0])
        expect(setting_on(conn)).to eq("50ms")
      end
    end

    # A statement can't turn the timeout off for the ones after it, since
    # each statement's own round trip arms it again.
    it "times a statement out after an earlier one turned the timeout off" do
      short = described_class.new(conn, statement_timeout_ms: 100)

      error = run_error(short) do |tx|
        tx.query("SELECT set_config('statement_timeout', '0', true)")
        tx.query("SELECT pg_sleep(5)")
      end

      expect([error.rule, error.sqlstate, error.step, error.index]).to eq([:statement_timeout, "57014", :query, 1])
      expect_nothing_persisted
    end

    # After a cancel, Cancel.rule's first ROLLBACK can't turn the timeout off,
    # since an aborted transaction refuses everything else. It doesn't need
    # to for the runner's own timeout: that's set for the transaction, and
    # Postgres drops such settings as the transaction aborts, so the ROLLBACK
    # runs under the session's setting. Under a nonzero one, a server slower
    # than that to reach the ROLLBACK cancels it, and the timeout reads as
    # statement_canceled (see DESIGN.md). This plants that delay as a
    # statement after the ROLLBACK in its query string: the server parses the
    # whole string, with the timeout armed, before it runs the ROLLBACK.
    describe "a first ROLLBACK after a cancel that the server is slow to reach" do
      let(:slow_first_rollback) do
        Class.new(SimpleDelegator) do
          def exec(sql, *, &)
            sql = "#{sql}; SELECT 1 WHERE 0 IN (#{Array.new(1_000_000, 1).join(",")})" if sql.start_with?("ROLLBACK; ")
            __getobj__.exec(sql, *, &)
          end
        end.new(conn)
      end

      def timed_out
        error = run_error(described_class.new(slow_first_rollback, statement_timeout_ms: 100)) do |tx|
          tx.query("SELECT pg_sleep(5)")
        end
        [error.rule, error.sqlstate, error.step, error.index, conn.transaction_status]
      end

      it "takes longer than the runner's timeout to reach" do
        conn.exec("SET statement_timeout = 100")
        expect { slow_first_rollback.exec("ROLLBACK; SELECT 1") }
          .to raise_error(PG::QueryCanceled) { expect(it.result.error_field(67)).to eq("57014") }
      end

      it "isn't canceled by the runner's timeout" do
        expect(timed_out).to eq([:statement_timeout, "57014", :query, 0, 0])
      end

      it "is canceled under a nonzero session timeout, and the timeout reads as statement_canceled" do
        conn.exec("SET statement_timeout = 50")

        expect(timed_out).to eq([:statement_canceled, "57014", :query, 0, 0])
        expect(session_timeout).to eq("50ms")
      end
    end

    # The closing ROLLBACK runs with the timeout off, so a server that takes
    # longer than the timeout to get to it, as a loaded one can, doesn't
    # cancel it and leave the transaction open. This plants that delay just
    # ahead of the ROLLBACK, in its own query string, where the timeout that
    # was armed for the ROLLBACK would fire on it.
    describe "a closing ROLLBACK the server is slow to reach" do
      let(:slow_rollback_class) do
        Class.new(SimpleDelegator) do
          def exec(sql, *, &)
            sql = "SELECT pg_sleep(0.3); #{sql}" if sql == "ROLLBACK"
            __getobj__.exec(sql, *, &)
          end
        end
      end

      let(:short) { described_class.new(slow_rollback_class.new(conn), statement_timeout_ms: 100) }

      it "rolls back after a fixture that ran no statement" do
        expect(short.with_fixture { :ran }).to eq(:ran)
        expect_nothing_persisted
      end

      it "rolls back after a block that returns" do
        expect(short.with_fixture([parent(1, "a")]) { |tx| tx.query("SELECT 7").rows }).to eq([["7"]])
        expect_nothing_persisted
      end

      it "rolls back after a block that raises, and keeps the block's error" do
        expect { short.with_fixture([parent(1, "a")]) { raise ArgumentError, "the block's own" } }
          .to raise_error(ArgumentError, "the block's own")
        expect_nothing_persisted
      end

      # The session's own timeout is off whenever no statement ran, so only
      # a nonzero one shows that the load turns it off.
      it "rolls back after a fixture that ran no statement, under a nonzero session timeout" do
        conn.exec("SET statement_timeout = 100")

        expect(short.with_fixture { :ran }).to eq(:ran)
        expect_nothing_persisted
        expect(session_timeout).to eq("100ms")
      end
    end

    # The timeout can fire just as a statement finishes. Postgres has then
    # sent the statement's result, and it reports the cancel on the next
    # message it handles: the reset that turns the timeout off after the
    # statement, or, if the reset has run, the pipeline's Sync. Either way
    # the error comes after the statement's result. That's a race, so this
    # plants the same shape: in the reset's place, or just before the
    # runner's Sync, it sends a statement that gets canceled.
    describe "a cancel that arrives after the statement's result" do
      let(:late_cancel_class) do
        Class.new(SimpleDelegator) do
          def initialize(conn, sql, place)
            super(conn)
            @sql = sql
            @place = place
          end

          def arm! = @armed = true

          def send_query_params(sql, params)
            if @armed && @place == :reset && sql == Quaack::Enclave::ArenaRunner::Pipeline::DISARM_SQL
              @armed = false
              sql = @sql
            end
            __getobj__.send_query_params(sql, params)
          end

          def pipeline_sync
            __getobj__.send_query_params(@sql, []) if @armed && @place == :sync
            @armed = false
            __getobj__.pipeline_sync
          end
        end
      end

      def late_cancel_error(sql, place, statement_timeout_ms:)
        late = late_cancel_class.new(conn, sql, place)
        short = described_class.new(late, statement_timeout_ms:)
        error = run_error(short, [parent(1, "a")]) do |tx|
          late.arm!
          tx.query("SELECT 1")
        end
        [error, short]
      end

      def expect_usable_after(short)
        expect(conn.pipeline_status).to eq(0)
        expect_nothing_persisted
        expect(short.with_fixture([parent(2, "b")]) { |tx| tx.query("SELECT 7").rows }).to eq([["7"]])
      end

      let(:self_cancel) { "SELECT pg_cancel_backend(pg_backend_pid()), pg_sleep(5)" }

      it "reports the timeout in the reset's place, leaves pipeline mode, and leaves the connection usable" do
        error, short = late_cancel_error("SELECT pg_sleep(5)", :reset, statement_timeout_ms: 100)

        expect([error.rule, error.sqlstate, error.step, error.index]).to eq([:statement_timeout, "57014", :query, 0])
        expect_usable_after(short)
      end

      it "reports another cancel in the reset's place as statement_canceled, and leaves the connection usable" do
        error, short = late_cancel_error(self_cancel, :reset, statement_timeout_ms: 5000)

        expect([error.rule, error.sqlstate, error.step, error.index]).to eq([:statement_canceled, "57014", :query, 0])
        expect_usable_after(short)
      end

      it "reports a cancel in the Sync's place, leaves pipeline mode, and leaves the connection usable" do
        error, short = late_cancel_error(self_cancel, :sync, statement_timeout_ms: 5000)

        expect([error.rule, error.sqlstate, error.step, error.index]).to eq([:statement_canceled, "57014", :query, 0])
        expect_usable_after(short)
      end

      # After a statement fails on its own, the reset comes back aborted and
      # nothing more runs before the Sync, so no planted statement can give
      # the late cancel. This hands back a real canceled result just before
      # the Sync's, faking only the edge. The cancel stands in for the
      # reset's result, and the statement's own error must still win.
      let(:late_result_class) do
        Class.new(SimpleDelegator) do
          def initialize(conn, late)
            super(conn)
            @late = late
            @held = []
          end

          def arm! = @armed = true

          def get_result # rubocop:disable Naming/AccessorMethodName -- PG::Connection's own name
            return @held.shift unless @held.empty?

            result = __getobj__.get_result
            return result unless @armed && result&.result_status == 10

            @armed = false
            @held = [nil, result]
            @late
          end
        end
      end

      it "keeps a statement's own error when a cancel comes after it, in the Sync's place" do
        conn.send_query(self_cancel)
        late = conn.get_result.tap { conn.get_result }
        expect(late.error_field(67)).to eq("57014")
        edge = late_result_class.new(conn, late)
        short = described_class.new(edge, statement_timeout_ms: 5000)

        error = run_error(short, [parent(1, "a")]) do |tx|
          edge.arm!
          tx.query("SELECT 1/0")
        end

        expect([error.rule, error.sqlstate, error.step, error.index]).to eq([:query_failed, "22012", :query, 0])
        expect_usable_after(short)
      end
    end

    # Telling a timeout by the server's clock mustn't slow fixture loads:
    # each statement's clock read goes in the statement's own round trip,
    # and nothing gives a statement a transaction ID of its own.
    describe "cost per statement" do
      let(:counting_class) do
        Class.new(SimpleDelegator) do
          attr_reader :round_trips

          def initialize(conn)
            super
            @round_trips = 0
          end

          %i[exec exec_params pipeline_sync].each do |name|
            define_method(name) do |*args, &block|
              @round_trips += 1
              __getobj__.public_send(name, *args, &block)
            end
          end
        end
      end

      def rows(count) = (1..count).map { parent(it, "c#{it}") }

      def round_trips(count)
        counting = counting_class.new(conn)
        described_class.new(counting).with_fixture(rows(count)) { |tx| 2.times { tx.query("SELECT 1") } }
        counting.round_trips
      end

      def next_xid = Integer(conn.exec("SELECT pg_snapshot_xmax(pg_current_snapshot())").getvalue(0, 0))

      it "takes one round trip per statement" do
        expect(round_trips(20) - round_trips(10)).to eq(10)
      end

      it "uses one transaction ID for the whole fixture" do
        before = next_xid
        runner.with_fixture(rows(10)) { |tx| 2.times { tx.query("SELECT 1") } }

        expect(next_xid - before).to eq(1)
      end
    end

    def canceler_name = "operator-canceler"

    # The canceler reports no errors of its own, so one that outlived its
    # example would die silently when the database is dropped. This runs
    # before that drop and fails if cancel_once_sleeping didn't stop it.
    after do
      expect(Thread.list.select { |t| t.name == canceler_name }).to be_empty, "the canceler thread outlived its example"
    end

    # Yields while a second session waits for conn to sit in pg_sleep, then
    # cancels it. If the block fails, raises the canceler's own error if it
    # died of one, and otherwise says so if the cancel never went out. The
    # canceler never outlives the example, so it can't die noisily later when
    # the after hook drops the database. Its connection opens here, not in the
    # thread, so a kill can't strand a half-open login that the drop waits on.
    def cancel_once_sleeping(&)
      other = arena.connect
      canceler = start_canceler(other, conn.backend_pid)
      result = name_early_failure(canceler, &)
      canceler.join
      result
    ensure
      stop(canceler) if canceler
      other&.close
    end

    def name_early_failure(canceler)
      yield
    rescue StandardError
      died_of = thread_error(canceler)
      raise died_of if died_of
      raise "the INSERT never reached pg_sleep" unless canceler[:cancel_sent]

      raise
    end

    # The error the thread died of, or nil if it's still running or ended
    # cleanly.
    def thread_error(thread)
      thread.join(0)
      nil
    rescue StandardError => e
      e
    end

    # cancel_sent is set before the cancel goes out, so a block that fails
    # from the cancel always finds it set.
    def start_canceler(other, pid)
      thread = Thread.new do
        Thread.current.report_on_exception = false
        wait_for_sleep(other, pid)
        Thread.current[:cancel_sent] = true
        other.exec_params("SELECT pg_cancel_backend($1::int)", [pid])
      end
      thread.name = canceler_name
      thread
    end

    def wait_for_sleep(other, pid)
      deadline = Process.clock_gettime(Process::CLOCK_MONOTONIC) + 10
      until other.exec_params(
        "SELECT count(*) FROM pg_stat_activity WHERE pid = $1 AND wait_event = 'PgSleep'", [pid]
      ).getvalue(0, 0) == "1"
        raise "the INSERT never reached pg_sleep" if Process.clock_gettime(Process::CLOCK_MONOTONIC) > deadline

        sleep 0.05
      end
    end

    def stop(thread)
      thread.kill.join
    rescue StandardError
      nil # Already raised by the join above, or superseded by the block's failure.
    end

    it "reports an operator's cancel from another session as statement_canceled, whatever the step" do
      error = cancel_once_sleeping do
        run_error(runner, [], inserts: ['INSERT INTO "Fixture Space".counters (label) SELECT pg_sleep(5)::text'])
      end

      expect([error.rule, error.sqlstate, error.step, error.index]).to eq([:statement_canceled, "57014", :insert, 0])
      expect_nothing_persisted
    end
  end

  describe "index scans" do
    let(:scan_settings) do
      "SELECT current_setting('enable_indexscan'), current_setting('enable_indexonlyscan'), " \
        "current_setting('enable_bitmapscan')"
    end

    def session_scans = conn.exec(scan_settings).values

    it "leaves index scans on by default" do
      expect(runner.with_fixture { |tx| tx.query(scan_settings).rows }).to eq([%w[on on on]])
    end

    it "turns index, index-only, and bitmap scans off for the transaction only, when asked" do
      inside = runner.with_fixture(index_scans: false) { |tx| tx.query(scan_settings).rows }

      expect(inside).to eq([%w[off off off]])
      expect(session_scans).to eq([%w[on on on]])
    end

    it "refuses an index_scans that isn't true or false" do
      expect { runner.with_fixture(index_scans: "off") }
        .to raise_error(ArgumentError, "index_scans must be true or false")
    end
  end

  describe "always rolling back" do
    it "rolls back after a query error, naming the query by its position" do
      error = run_error(runner, [parent(1, "a")]) do |tx|
        tx.query("SELECT 1")
        tx.query('SELECT 1 / (id - id) FROM "Fixture Space"."Parent Rows"')
      end

      expect([error.rule, error.sqlstate, error.step, error.index]).to eq([:query_failed, "22012", :query, 1])
      expect(error.message).to eq("a query failed in the arena transaction")
      expect_nothing_persisted
    end

    # An error that isn't a cancel leaves the transaction aborted, not
    # rolled back, so it's still the runner's: a query after it goes out
    # and fails as it would on its own.
    it "fails a query after a caught error with 25P02, and rolls back" do
      write = 'WITH d AS (INSERT INTO "Fixture Space".counters DEFAULT VALUES RETURNING id) SELECT 1'
      errors = []
      runner.with_fixture([parent(1, "a")]) do |tx|
        ["SELECT 1 / 0", write].each do |sql|
          tx.query(sql)
        rescue described_class::Error => e
          errors << e
        end
      end

      expect(errors.map { [it.rule, it.index, it.sqlstate] })
        .to eq([[:query_failed, 0, "22012"], [:query_failed, 1, "25P02"]])
      expect_nothing_persisted
    end

    it "rolls back after a fixture row fails to load, naming the row by its position" do
      error = run_error(runner, [parent(1, "a"), child(10, "a"), parent(2, "a")]) { raise "not reached" }

      expect([error.rule, error.sqlstate, error.step, error.index]).to eq([:fixture_load_failed, "23505", :load, 2])
      expect_nothing_persisted
    end

    it "rolls back after a raw INSERT statement fails" do
      inserts = ['INSERT INTO "Fixture Space".children VALUES (20, \'a\', 2)',
                 'INSERT INTO "Fixture Space".children VALUES (21, \'missing\', 3)']

      error = run_error(runner, [parent(1, "a")], inserts: inserts) { raise "not reached" }

      expect([error.rule, error.sqlstate, error.step, error.index]).to eq([:insert_failed, "23503", :insert, 1])
      expect_nothing_persisted
    end

    it "rolls back and lets the block's own exception through untouched" do
      failure = Class.new(StandardError)

      expect do
        runner.with_fixture([parent(1, "a")]) do |tx|
          tx.query("SELECT 1")
          raise failure, "from the block"
        end
      end.to raise_error(failure, "from the block")
      expect_nothing_persisted
    end

    # The statement check refuses COMMIT and the like before they run, so
    # this reaches past it to the backstop that checks the transaction is
    # still open after every statement.
    it "reports a statement that ended the transaction, as a backstop to the statement check" do
      # Inside a caller's rescue, so a missing cause: nil would show.
      error = begin
        raise sentinel
      rescue StandardError
        run_error { runner.__send__(:statement, "COMMIT", [], step: :query, rule: :query_failed, index: 3) }
      end

      expect([error.rule, error.step, error.index, error.cause]).to eq([:transaction_ended, :query, 3, nil])
      expect(conn.transaction_status).to eq(0)
      # SET LOCAL ends with the transaction, even one that was committed.
      expect(session_timeout).to eq("0")
    end

    # Only an idle connection means a statement ended the transaction. A
    # statement that succeeded can't leave it aborted (PQTRANS_INERROR, 3),
    # so libpq reporting that afterwards means the connection's state can't
    # be trusted. This fakes only the connection's status, at the check
    # after the first query: the first read is with_fixture's, and each
    # statement reads it before and after.
    it "reports a transaction aborted after a statement that succeeded as connection_unusable" do
      aborted = Class.new(SimpleDelegator) do
        def transaction_status
          @reads = (@reads || 0) + 1
          @reads == 3 ? 3 : __getobj__.transaction_status
        end
      end.new(conn)

      error = run_error(described_class.new(aborted)) { |tx| tx.query("SELECT 1") }

      expect([error.rule, error.step, error.index, error.cause]).to eq([:connection_unusable, :query, 0, nil])
      expect_nothing_persisted
    end

    it "refuses a string of several statements in the backstop too" do
      error = run_error do
        runner.__send__(:statement, 'SELECT 1; INSERT INTO "Fixture Space".counters DEFAULT VALUES', [],
                        step: :query, rule: :query_failed, index: 0)
      end

      expect([error.rule, error.sqlstate]).to eq([:query_failed, "42601"])
      expect_nothing_persisted
    end

    it "keeps the block's own exception when the connection dies and the rollback fails too" do
      failure = Class.new(StandardError)

      expect do
        runner.with_fixture([parent(1, "a")]) do
          terminate(conn)
          raise failure, "from the block"
        end
      end.to raise_error(failure, "from the block")
      expect(persisted_rows).to eq(0)
    end

    # Interrupt isn't a StandardError, so this needs the runner to note any
    # exception, not just a StandardError, before it tries to roll back.
    it "keeps an Interrupt from the block when the connection dies and the rollback fails too" do
      expect do
        runner.with_fixture([parent(1, "a")]) do
          terminate(conn)
          raise Interrupt, "from the block"
        end
      end.to raise_error(Interrupt, "from the block")
      expect(persisted_rows).to eq(0)
    end

    it "keeps the query's own error when the connection dies and the rollback fails too" do
      error = run_error(runner, [parent(1, "a")]) do |tx|
        terminate(conn)
        tx.query("SELECT 1")
      end

      expect([error.rule, error.step, error.index, error.cause]).to eq([:query_failed, :query, 0, nil])
      expect(persisted_rows).to eq(0)
      # The dead connection is left in pipeline mode (PQ_PIPELINE_ABORTED,
      # 2), and libpq reports its transaction status as PQTRANS_UNKNOWN, so
      # the runner refuses it before sending anything.
      expect([conn.pipeline_status, conn.transaction_status]).to eq([2, 4])
      expect([run_error.rule, run_error.step]).to eq(%i[connection_unusable transaction])
    end

    # A caller that catches the error and goes on finds the connection
    # dead, not the transaction ended by a statement.
    it "reports a query after the connection died as connection_unusable" do
      errors = []
      rollback = run_error(runner, [parent(1, "a")]) do |tx|
        terminate(conn)
        2.times do
          tx.query("SELECT 1")
        rescue described_class::Error => e
          errors << e
        end
      end

      expect(errors.map { [it.rule, it.step, it.index, it.sqlstate, it.cause] })
        .to eq([[:query_failed, :query, 0, nil, nil], [:connection_unusable, :query, 1, nil, nil]])
      expect(errors.last.message).to eq("the arena connection stopped working partway through the arena transaction")
      expect(rollback.rule).to eq(:rollback_failed)
    end

    it "refuses a query through the transaction after the block has returned" do
      kept = nil
      runner.with_fixture { |tx| kept = tx }

      expect { kept.query('INSERT INTO "Fixture Space".counters DEFAULT VALUES') }
        .to raise_error(described_class::Error) { |e| expect(e.rule).to eq(:transaction_closed) }
      expect_nothing_persisted
    end

    it "turns a rollback that fails into its own error" do
      other = arena.connect

      error = run_error(described_class.new(other)) { other.close }

      expect([error.rule, error.sqlstate, error.step, error.cause]).to eq([:rollback_failed, nil, :rollback, nil])
    end
  end

  # Ends conn's backend from another session, the way a crash or an
  # operator would.
  def terminate(victim)
    pid = victim.backend_pid
    killer = arena.connect
    # Waits up to five seconds for the backend to be gone.
    killer.exec_params("SELECT pg_terminate_backend($1::int, 5000)", [pid])
  ensure
    killer&.close
  end

  describe "a connection that can't start a transaction" do
    let(:start_refusal) { "the arena connection can't start a transaction: it's closed, broken, or busy" }

    it "reports a closed connection as unusable" do
      other = arena.connect
      other.close

      error = run_error(described_class.new(other))

      expect([error.rule, error.step, error.sqlstate, error.cause, error.message])
        .to eq([:connection_unusable, :transaction, nil, nil, start_refusal])
    end

    # PQTRANS_UNKNOWN is 4: libpq has seen the connection go bad.
    it "reports a dead connection as unusable" do
      other = arena.connect
      terminate(other)
      begin
        other.exec("SELECT 1")
      rescue StandardError
        nil
      end
      expect(other.transaction_status).to eq(4)

      error = run_error(described_class.new(other))

      expect([error.rule, error.step, error.message]).to eq([:connection_unusable, :transaction, start_refusal])
    ensure
      other&.close
    end

    # PQTRANS_ACTIVE is 1: a query was sent and its result not yet read.
    it "reports a connection busy with a query as unusable, and leaves the query alone" do
      conn.send_query("SELECT 42")
      expect(conn.transaction_status).to eq(1)

      error = run_error

      expect([error.rule, error.step, error.message]).to eq([:connection_unusable, :transaction, start_refusal])
      expect(conn.get_result.getvalue(0, 0)).to eq("42")
      conn.get_result
    end
  end

  describe "a connection already inside a transaction" do
    it "refuses inside a caller's rescue without taking the caller's exception as its cause" do
      conn.exec("BEGIN")

      error = begin
        raise sentinel
      rescue StandardError
        run_error
      end

      expect([error.rule, error.cause]).to eq([:already_in_transaction, nil])
      conn.exec("ROLLBACK")
    end

    it "refuses a connection in a failed transaction too" do
      conn.exec("BEGIN")
      begin
        conn.exec("SELECT 1 / 0")
      rescue StandardError
        nil
      end
      expect(conn.transaction_status).to eq(3)

      expect(run_error.rule).to eq(:already_in_transaction)
      conn.exec("ROLLBACK")
    end

    it "refuses, and leaves that transaction alone" do
      conn.exec("BEGIN")
      conn.exec('INSERT INTO "Fixture Space".counters DEFAULT VALUES')
      yielded = false

      error = run_error { yielded = true }

      expect([error.rule, yielded]).to eq([:already_in_transaction, false])
      expect(conn.transaction_status).to eq(2)
      expect(conn.exec('SELECT count(*) FROM "Fixture Space".counters').getvalue(0, 0)).to eq("1")
      conn.exec("ROLLBACK")
    end
  end

  describe "fixture rows" do
    it "refuses a row whose columns and values don't line up, without naming the values" do
      expect { described_class::FixtureRow.new(table: parents, columns: %w[id note], values: [sentinel]) }
        .to raise_error(ArgumentError, "a fixture row needs one value per column")
    end

    it "refuses values that aren't Strings or nil, without naming them" do
      expect { described_class::FixtureRow.new(table: parents, columns: ["id"], values: [7]) }
        .to raise_error(ArgumentError, "fixture row values must be Strings or nil")
    end

    it "refuses a table that isn't a TableName, and column names that aren't non-empty Strings" do
      expect { described_class::FixtureRow.new(table: "public.t", columns: [], values: []) }
        .to raise_error(ArgumentError, "a fixture row's table must be a TableName")
      [[""], [:id]].each do |columns|
        expect { described_class::FixtureRow.new(table: parents, columns: columns, values: [nil]) }
          .to raise_error(ArgumentError, "fixture row columns must be non-empty Strings"), columns.inspect
      end
    end
  end

  # Postgres puts real values in its errors: a unique violation's DETAIL has
  # the key, and a check violation's has the whole row. None of it may reach
  # the runner's errors.
  describe "errors never carry values" do
    # Everything an error shows, down its cause chain.
    def texts_of(error)
      texts = []
      while error
        texts.push(error.message, error.full_message, error.detailed_message, error.inspect)
        %i[rule sqlstate step index].each { |field| texts << error.public_send(field).to_s if error.respond_to?(field) }
        error = error.cause
      end
      texts
    end

    # The same failure straight through the connection, to prove Postgres
    # really does put the sentinel in its error, so texts_of would find it.
    def raw_error(sql, params = [])
      other = arena.connect
      other.exec("BEGIN")
      other.exec_params(sql, params)
      raise "expected a database error"
    rescue StandardError => e
      e
    ensure
      other&.close
    end

    def expect_no_sentinel(error)
      expect(error).to be_a(described_class::Error)
      expect(error.cause).to be_nil
      expect(texts_of(error).grep(/#{sentinel}/)).to be_empty
    end

    def expect_sentinel_in_raw(sql, params = [])
      expect(texts_of(raw_error(sql, params)).grep(/#{sentinel}/)).not_to be_empty
    end

    it "keeps a colliding unique key out of the error" do
      error = run_error(runner, [parent(1, sentinel), parent(2, sentinel)])

      expect([error.rule, error.sqlstate]).to eq([:fixture_load_failed, "23505"])
      expect_no_sentinel(error)
      expect_sentinel_in_raw(<<~SQL, [sentinel])
        INSERT INTO "Fixture Space"."Parent Rows" (id, "Code") VALUES (1, $1), (2, $1)
      SQL
    end

    it "keeps a CHECK-violating row out of the error" do
      error = run_error(runner, [parent(1, "a", qty: -1, note: sentinel)])

      expect([error.rule, error.sqlstate]).to eq([:fixture_load_failed, "23514"])
      expect_no_sentinel(error)
      expect_sentinel_in_raw(<<~SQL, [sentinel])
        INSERT INTO "Fixture Space"."Parent Rows" (id, "Code", qty, note) VALUES (1, 'a', -1, $1)
      SQL
    end

    it "keeps a NOT NULL-violating row out of the error" do
      error = run_error(runner, [parent(1, nil, note: sentinel)])

      expect([error.rule, error.sqlstate]).to eq([:fixture_load_failed, "23502"])
      expect_no_sentinel(error)
      expect_sentinel_in_raw(<<~SQL, [sentinel])
        INSERT INTO "Fixture Space"."Parent Rows" (id, "Code", note) VALUES (1, NULL, $1)
      SQL
    end

    it "keeps a missing foreign key out of the error" do
      error = run_error(runner, [child(10, sentinel)])

      expect([error.rule, error.sqlstate]).to eq([:fixture_load_failed, "23503"])
      expect_no_sentinel(error)
      expect_sentinel_in_raw('INSERT INTO "Fixture Space".children (id, parent_code) VALUES (10, $1)', [sentinel])
    end

    it "keeps a raw INSERT statement's values out of the error" do
      sql = %(INSERT INTO "Fixture Space".children (id, parent_code) VALUES (10, '#{sentinel}'))

      error = run_error(runner, [], inserts: [sql])

      expect([error.rule, error.sqlstate]).to eq([:insert_failed, "23503"])
      expect_no_sentinel(error)
      expect_sentinel_in_raw(sql)
    end

    it "keeps a failing query's values and column names out of the error" do
      queries = [%(SELECT '#{sentinel}' AS "#{sentinel}", 1 / 0 AS "#{sentinel}-2"),
                 %(SELECT '#{sentinel}'::integer AS "#{sentinel}")]

      queries.each do |sql|
        error = run_error { |tx| tx.query(sql) }

        expect(error.rule).to eq(:query_failed)
        expect_no_sentinel(error)
      end
      expect_sentinel_in_raw(queries.last)
    end
  end

  # Only an INSERT may load and only a SELECT may query, so a COMMIT, or a
  # COMMIT AND CHAIN that would open a new transaction without the timeout,
  # never runs.
  describe "the statement check" do
    let(:refused) do
      ["COMMIT", "END", "ROLLBACK", "COMMIT AND CHAIN", "SAVEPOINT s", "PREPARE TRANSACTION 'quaack'",
       "SET statement_timeout = 0", "SHOW statement_timeout",
       'SELECT 1; INSERT INTO "Fixture Space".counters DEFAULT VALUES', "SELECT 1; SELECT 2",
       'INSERT INTO "Fixture Space".counters DEFAULT VALUES; INSERT INTO "Fixture Space".counters DEFAULT VALUES',
       'INSERT INTO "Fixture Space".counters DEFAULT VALUES; COMMIT', ""]
    end

    it "refuses anything but a single SELECT as a query, before it runs, and the transaction goes on" do
      refused.each do |sql|
        seen = runner.with_fixture([parent(1, "a")]) do |tx|
          error = begin
            tx.query(sql)
            nil
          rescue described_class::Error => e
            e
          end
          [error&.rule, error&.step, error&.index, conn.transaction_status, tx.query(timeout_sql).rows]
        end

        expect(seen).to eq([:statement_not_allowed, :query, 0, 2, [["10s"]]]), sql
        expect_nothing_persisted
        expect(session_timeout).to eq("0")
      end
    end

    it "refuses an INSERT as a query" do
      error = run_error { |tx| tx.query('INSERT INTO "Fixture Space".counters DEFAULT VALUES') }

      expect(error.rule).to eq(:statement_not_allowed)
      expect_nothing_persisted
    end

    it "refuses anything but a single INSERT among the inserts, before the transaction starts" do
      (refused + ["SELECT 1"]).each do |sql|
        yielded = false
        inserts = ['INSERT INTO "Fixture Space".counters DEFAULT VALUES', sql]

        error = run_error(runner, [parent(1, "a")], inserts: inserts) { yielded = true }

        expect([error.rule, error.step, error.index, yielded]).to eq([:statement_not_allowed, :insert, 1, false]), sql
        expect_nothing_persisted
        expect(session_timeout).to eq("0")
      end
    end

    it "accepts an INSERT with a WITH clause and a SELECT with one" do
      inserts = ['WITH v(id) AS (VALUES (5)) INSERT INTO "Fixture Space".counters (id) SELECT id FROM v']

      rows = runner.with_fixture([], inserts: inserts) do |tx|
        tx.query('WITH c AS (SELECT id FROM "Fixture Space".counters) SELECT id FROM c').rows
      end

      expect(rows).to eq([["5"]])
      expect_nothing_persisted
    end

    it "reports SQL it can't parse without repeating it" do
      sql = "SELECT '#{sentinel}' '#{sentinel}'"

      query_error = run_error { |tx| tx.query(sql) }
      insert_error = run_error(runner, [], inserts: [sql])

      [[query_error, :query], [insert_error, :insert]].each do |error, step|
        expect([error.rule, error.step, error.index, error.cause]).to eq([:statement_unparsable, step, 0, nil])
        expect([error.message, error.full_message, error.inspect].grep(/#{sentinel}/)).to be_empty
      end
      expect { PgQuery.parse(sql) }.to raise_error(PgQuery::ParseError, /#{sentinel}/)
    end

    it "refuses a query and an insert that aren't Strings or DeferredInserts" do
      expect { runner.with_fixture { |tx| tx.query(:select) } }
        .to raise_error(ArgumentError, "a query must be a String")
      [[:insert], "INSERT", [{ sql: "INSERT", updates: [] }]].each do |inserts|
        expect { runner.with_fixture([], inserts: inserts) { raise "not reached" } }
          .to raise_error(ArgumentError, "inserts must be an Array of Strings or DeferredInserts"), inserts.inspect
      end
      expect_nothing_persisted
    end

    it "refuses a DeferredInsert whose sql isn't a String or whose updates aren't Hashes of Strings" do
      deferred = described_class::DeferredInsert
      expect { deferred.new(sql: :insert, updates: []) }
        .to raise_error(ArgumentError, "a deferred insert's sql must be a String")
      [{ "a" => "b" }, [[%w[a b]]], [{ "a" => 1 }], [{ a: "b" }]].each do |updates|
        expect { deferred.new(sql: "INSERT", updates:) }
          .to raise_error(ArgumentError, "a deferred insert's updates must be String Hashes"), updates.inspect
      end
      expect(deferred.new(sql: "INSERT", updates: [{ "a" => "b" }, {}]).updates).to eq([{ "a" => "b" }, {}])
    end

    it "checks a DeferredInsert's sql before the transaction starts, and never shows its values" do
      deferred = described_class::DeferredInsert.new(sql: "SELECT '#{sentinel}'", updates: [{ "a" => sentinel }])

      error = run_error(inserts: [deferred])

      expect([error.rule, error.step, error.index]).to eq([:statement_not_allowed, :insert, 0])
      expect([deferred.inspect, deferred.to_s, error.message].grep(/#{sentinel}/)).to be_empty
      expect_nothing_persisted
    end

    it "refuses inside a caller's rescue without taking the caller's exception as its cause" do
      errors = runner.with_fixture do |tx|
        [proc { tx.query("COMMIT") }, proc { tx.query("SELECT FROM WHERE") }].map do |bad|
          raise sentinel
        rescue StandardError
          begin
            bad.call
          rescue described_class::Error => e
            e
          end
        end
      end

      expect(errors.map { |e| [e.rule, e.cause] }).to eq([[:statement_not_allowed, nil], [:statement_unparsable, nil]])
    end
  end

  describe "the fixture itself" do
    # Checked before the connection is, so bad rows are refused as bad rows
    # even on a connection that's busy.
    it "refuses bad rows before it looks at a connection already inside a transaction" do
      conn.exec("BEGIN")
      yielded = false

      expect { runner.with_fixture([:junk]) { yielded = true } }
        .to raise_error(ArgumentError, "rows must be an Array of FixtureRows")
      expect([yielded, conn.transaction_status]).to eq([false, 2])
      conn.exec("ROLLBACK")
    end

    it "refuses rows that aren't FixtureRows before the transaction starts" do
      [[:junk], [parent(1, "a"), "row"], :junk, {}].each do |rows|
        yielded = false

        expect { runner.with_fixture(rows) { yielded = true } }
          .to raise_error(ArgumentError, "rows must be an Array of FixtureRows"), rows.inspect
        expect(yielded).to be(false)
        expect_nothing_persisted
      end
    end
  end

  describe "fixture row copies" do
    it "keeps its own frozen copies of the columns and values" do
      columns = [+"id", +"Code"]
      values = [+"1", nil]

      fixture_row = described_class::FixtureRow.new(table: parents, columns: columns, values: values)
      columns.first << "x"
      columns << "qty"
      values.first << "2"
      values << "3"

      expect([fixture_row.columns, fixture_row.values]).to eq([%w[id Code], ["1", nil]])
      expect([fixture_row.columns, fixture_row.values, fixture_row.columns.first, fixture_row.values.first])
        .to all(be_frozen)
    end

    it "refuses columns or values that aren't Arrays" do
      expect { described_class::FixtureRow.new(table: parents, columns: "id", values: ["1"]) }
        .to raise_error(ArgumentError, "fixture row columns must be non-empty Strings")
      [nil, "1", { "id" => "1" }].each do |values|
        expect { described_class::FixtureRow.new(table: parents, columns: ["id"], values: values) }
          .to raise_error(ArgumentError, "a fixture row needs one value per column"), values.inspect
      end
    end
  end

  describe "the transaction handle" do
    it "refuses after the block inside a caller's rescue without taking its exception as the cause" do
      kept = nil
      runner.with_fixture { |tx| kept = tx }

      error = begin
        raise sentinel
      rescue StandardError
        begin
          kept.query("SELECT 1")
        rescue described_class::Error => e
          e
        end
      end

      expect([error.rule, error.cause]).to eq([:transaction_closed, nil])
    end
  end

  # Postgres notices go to stderr through libpq's default receiver, and the
  # enclave's stderr reaches the laptop. A notice can carry a real value, as
  # shout's does here from a table CHECK, a domain CHECK, and a query.
  describe "notices" do
    let(:noisy) { Quaack::Enclave::TableName.new(schema: "Fixture Space", name: "noisy") }

    before do
      conn.exec(<<~SQL)
        CREATE FUNCTION "Fixture Space".shout(v text) RETURNS boolean IMMUTABLE LANGUAGE plpgsql AS $$
          BEGIN RAISE NOTICE 'VAL=%', v; RETURN true; END
        $$;
        CREATE DOMAIN "Fixture Space".loud AS text CHECK ("Fixture Space".shout(VALUE));
        CREATE TABLE "Fixture Space".noisy (id integer PRIMARY KEY, a text CHECK ("Fixture Space".shout(a)),
                                            b "Fixture Space".loud);
      SQL
    end

    def noisy_run
      rows = [row(noisy, { "id" => "1", "a" => "#{sentinel}-check", "b" => "#{sentinel}-domain" })]
      runner.with_fixture(rows) do |tx|
        tx.query(%(SELECT "Fixture Space".shout('#{sentinel}-query')))
        tx.query('SELECT a, b FROM "Fixture Space".noisy').rows
      end
    end

    def shout(word) = conn.exec(%(SELECT "Fixture Space".shout('#{word}')))

    # Everything written to fd 2, where libpq's default receiver writes.
    def fd2
      saved = $stderr.dup
      Tempfile.create("arena-stderr") do |file|
        $stderr.reopen(file)
        yield
        $stderr.flush
        file.rewind
        return file.read
      ensure
        $stderr.reopen(saved)
      end
    end

    it "drops them while it runs, and puts the default receiver back" do
      loaded = nil
      written = fd2 do
        shout("before")
        loaded = noisy_run
        shout("after")
      end

      expect(loaded).to eq([["#{sentinel}-check", "#{sentinel}-domain"]])
      expect(written).to include("VAL=before").and include("VAL=after")
      expect(written).not_to include(sentinel)
      expect(conn.set_notice_receiver { nil }).to be_nil
    end

    it "drops them while it runs, and puts a caller's receiver back" do
      heard = []
      conn.set_notice_receiver { |result| heard << result.error_message }

      shout("before")
      noisy_run
      shout("after")

      expect(heard.join).to include("VAL=before").and include("VAL=after")
      expect(heard.grep(/#{sentinel}/)).to be_empty
      expect(heard.size).to eq(2)
    end

    it "puts the receiver back after a failure too" do
      heard = []
      conn.set_notice_receiver { |result| heard << result.error_message }

      run_error { |tx| tx.query("SELECT 1 / 0") }
      shout("after")

      expect(heard.join).to include("VAL=after")
    end
  end

  # A connection that fails one chosen call with an error that isn't
  # Postgres's and that carries the sentinel, the way a driver-level fault
  # might. It fakes only the edge. Everything else goes to the real
  # connection.
  describe "a connection call that fails with some other error" do
    let(:flaky_class) do
      Class.new(SimpleDelegator) do
        def initialize(conn, method, call, message)
          super(conn)
          @fail = [method, call]
          @message = message
          @calls = Hash.new(0)
        end

        %i[exec send_query_params transaction_status set_notice_receiver].each do |name|
          define_method(name) do |*args, &block|
            @calls[name] += 1
            raise IOError, @message if @fail == [name, @calls[name]]

            __getobj__.public_send(name, *args, &block)
          end
        end
      end
    end

    def flaky_error(method, call)
      flaky = flaky_class.new(conn, method, call, sentinel)
      run_error(described_class.new(flaky), [parent(1, "a"), parent(2, "b")])
    end

    it "reports each by its phase, with no SQLSTATE and nothing from the error" do
      cases = {
        [:transaction_status, 1] => [:connection_unusable, :transaction, nil],
        [:set_notice_receiver, 1] => [:connection_unusable, :transaction, nil],
        [:exec, 1] => [:begin_failed, :begin, nil],
        [:exec, 2] => [:begin_failed, :begin, nil],
        # Each statement sends the server's clock, itself, and the timeout's
        # reset.
        [:send_query_params, 10] => [:fixture_load_failed, :load, 1], # after two setvals (id, qty)
        [:send_query_params, 11] => [:fixture_load_failed, :load, 1],
        [:send_query_params, 12] => [:fixture_load_failed, :load, 1],
        # Each statement reads the transaction status before it's sent and
        # after it's run: after two setvals, the first row's.
        [:transaction_status, 6] => [:fixture_load_failed, :load, 0],
        [:transaction_status, 7] => [:fixture_load_failed, :load, 0]
      }

      cases.each do |(method, call), expected|
        error = flaky_error(method, call)

        seen = [error.rule, error.step, error.index, error.sqlstate, error.cause]
        expect(seen).to eq([*expected, nil, nil]), [method, call].inspect
        expect([error.message, error.full_message, error.inspect].grep(/#{sentinel}/)).to be_empty
        expect_nothing_persisted
      end
    end

    # After a cancel, the runner reads the server's clock again to tell a
    # timeout from another cancel. If that read fails, the cancel can't be
    # shown to be the timeout, and the read's error goes nowhere.
    it "reports a cancel as statement_canceled when the server's clock can't be read after it" do
      clockless = Class.new(SimpleDelegator) do
        def initialize(conn, message)
          super(conn)
          @message = message
        end

        def exec(sql, *, &)
          raise IOError, @message if sql.include?("clock_timestamp")

          __getobj__.exec(sql, *, &)
        end
      end.new(conn, sentinel)
      short = described_class.new(clockless, statement_timeout_ms: 100)

      error = run_error(short, [parent(1, "a")]) { |tx| tx.query("SELECT pg_sleep(5)") }

      expect([error.rule, error.sqlstate, error.step, error.index, error.cause])
        .to eq([:statement_canceled, "57014", :query, 0, nil])
      expect([error.message, error.full_message, error.inspect].grep(/#{sentinel}/)).to be_empty
      expect_nothing_persisted
    end
  end
end
