# frozen_string_literal: true

require "quaack/enclave/arena_runner"
require "quaack/enclave/table_name"

# Steps 9a, 9b, and 9e against a real arena database: open a transaction
# with statement_timeout, load a fixture, run queries, and always roll back.
RSpec.describe Quaack::Enclave::ArenaRunner do
  let(:arena) { racetrack_and_arena.arena }
  let(:conn) { arena.connection }
  let(:runner) { described_class.new(conn) }

  # Planted in fixture values and queries. It must never show up in an error.
  let(:sentinel) { "SENTINEL-7f3a9c" }

  let(:parents) { Quaack::Enclave::TableName.new(schema: "Fixture Space", name: "Parent Rows") }
  let(:children) { Quaack::Enclave::TableName.new(schema: "Fixture Space", name: "children") }
  let(:counters) { Quaack::Enclave::TableName.new(schema: "Fixture Space", name: "counters") }

  # A mixed-case schema and table with spaces, so the INSERTs must quote.
  before do
    conn.exec(<<~SQL)
      CREATE SCHEMA "Fixture Space";
      CREATE TABLE "Fixture Space"."Parent Rows" (
        id integer PRIMARY KEY,
        "Code" text NOT NULL UNIQUE,
        qty integer CHECK (qty > 0),
        note text
      );
      CREATE TABLE "Fixture Space".children (
        id integer PRIMARY KEY,
        parent_code text NOT NULL REFERENCES "Fixture Space"."Parent Rows" ("Code"),
        price numeric
      );
      CREATE TABLE "Fixture Space".counters (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        label text NOT NULL DEFAULT 'none'
      );
    SQL
  end

  def row(table, values)
    described_class::FixtureRow.new(table: table, columns: values.keys, values: values.values)
  end

  def parent(id, code, qty: 1, note: nil)
    row(parents, { "id" => id.to_s, "Code" => code, "qty" => qty&.to_s, "note" => note })
  end

  def child(id, code, price: nil) = row(children, { "id" => id.to_s, "parent_code" => code, "price" => price })

  # Counted from a fresh connection, so it sees only what was committed.
  def persisted_rows
    other = arena.connect
    other.exec(<<~SQL).getvalue(0, 0).to_i
      SELECT (SELECT count(*) FROM "Fixture Space"."Parent Rows")
           + (SELECT count(*) FROM "Fixture Space".children)
           + (SELECT count(*) FROM "Fixture Space".counters)
    SQL
  ensure
    other&.close
  end

  # PQTRANS_IDLE is 0 and PQTRANS_INTRANS is 2, from libpq.
  def expect_nothing_persisted
    expect(conn.transaction_status).to eq(0)
    expect(persisted_rows).to eq(0)
  end

  def run_error(runner = self.runner, rows = [], **, &block)
    block ||= proc {}
    runner.with_fixture(rows, **, &block)
    raise "expected ArenaRunner::Error"
  rescue described_class::Error => e
    e
  end

  describe "loading and querying" do
    it "loads the rows in order and returns each query's columns, type OIDs, and text rows" do
      rows = [parent(1, "a", note: "first"), parent(2, "b", qty: nil), child(10, "a", price: "1.50"), child(11, "b")]

      result = runner.with_fixture(rows) do |tx|
        tx.query('SELECT p.id, p."Code", p.qty, c.price FROM "Fixture Space"."Parent Rows" p ' \
                 'JOIN "Fixture Space".children c ON c.parent_code = p."Code" ORDER BY p.id')
      end

      expect(result).to eq(described_class::Result.new(
                             columns: %w[id Code qty price], types: [23, 25, 23, 1700],
                             rows: [["1", "a", "1", "1.50"], ["2", "b", nil, nil]]
                           ))
      expect_nothing_persisted
    end

    it "runs several queries against one loaded fixture and returns the block's value" do
      counts = runner.with_fixture([parent(1, "a"), parent(2, "b")]) do |tx|
        sql = 'SELECT count(*) FROM "Fixture Space"."Parent Rows" WHERE %s'
        [tx.query(format(sql, "qty = 1")), tx.query(format(sql, "TRUE")), tx.query(format(sql, "id = 2"))]
          .map { |r| r.rows.dig(0, 0) }
      end

      expect(counts).to eq(%w[2 2 1])
      expect_nothing_persisted
    end

    it "runs raw INSERT statements after the rows, each on its own" do
      inserts = ['INSERT INTO "Fixture Space".children VALUES (20, \'a\', 2)',
                 'INSERT INTO "Fixture Space".children VALUES (21, \'a\', 3)']

      rows = runner.with_fixture([parent(1, "a")], inserts: inserts) do |tx|
        tx.query('SELECT id, price FROM "Fixture Space".children ORDER BY id').rows
      end

      expect(rows).to eq([%w[20 2], %w[21 3]])
      expect_nothing_persisted
    end

    it "inserts a row with no columns as DEFAULT VALUES" do
      rows = runner.with_fixture([row(counters, {})]) do |tx|
        tx.query('SELECT id, label FROM "Fixture Space".counters').rows
      end

      expect(rows).to eq([%w[1 none]])
      expect_nothing_persisted
    end

    it "retries with rebuilt rows after a rollback, on the same connection" do
      sql = 'SELECT "Code" FROM "Fixture Space"."Parent Rows"'

      codes = %w[a z].map { |code| runner.with_fixture([parent(1, code)]) { |tx| tx.query(sql).rows } }

      expect(codes).to eq([[["a"]], [["z"]]])
      expect_nothing_persisted
    end
  end

  describe "statement_timeout" do
    it "defaults to 10 seconds, set only for the transaction" do
      inside = runner.with_fixture { |tx| tx.query("SHOW statement_timeout").rows }

      expect(inside).to eq([["10s"]])
      expect(conn.exec("SHOW statement_timeout").getvalue(0, 0)).to eq("0")
    end

    it "takes the timeout in milliseconds" do
      runner = described_class.new(conn, statement_timeout_ms: 250)

      inside = runner.with_fixture { |tx| tx.query("SHOW statement_timeout").rows }

      expect(inside).to eq([["250ms"]])
    end

    it "refuses a timeout that isn't a positive Integer" do
      [0, -5, 1.5, "100", nil].each do |bad|
        expect { described_class.new(conn, statement_timeout_ms: bad) }
          .to raise_error(ArgumentError, "statement_timeout_ms must be a positive Integer"), bad.inspect
      end
    end

    it "turns a timed-out query into a statement_timeout error and rolls back" do
      short = described_class.new(conn, statement_timeout_ms: 100)

      error = run_error(short, [parent(1, "a")]) { |tx| tx.query("SELECT pg_sleep(5)") }

      expect([error.rule, error.sqlstate, error.step, error.index]).to eq([:statement_timeout, "57014", :query, 0])
      expect_nothing_persisted
    end
  end

  describe "always rolling back" do
    it "rolls back after a query error, naming the query by its position" do
      error = run_error(runner, [parent(1, "a")]) do |tx|
        tx.query("SELECT 1")
        tx.query('SELECT 1 / (id - id) FROM "Fixture Space"."Parent Rows"')
      end

      expect([error.rule, error.sqlstate, error.step, error.index]).to eq([:query_failed, "22012", :query, 1])
      expect(error.message).to eq("a query failed in the arena transaction")
      expect_nothing_persisted
    end

    it "rolls back after a fixture row fails to load, naming the row by its position" do
      error = run_error(runner, [parent(1, "a"), child(10, "a"), parent(2, "a")]) { raise "not reached" }

      expect([error.rule, error.sqlstate, error.step, error.index]).to eq([:fixture_load_failed, "23505", :load, 2])
      expect_nothing_persisted
    end

    it "rolls back after a raw INSERT statement fails" do
      inserts = ['INSERT INTO "Fixture Space".children VALUES (20, \'a\', 2)',
                 'INSERT INTO "Fixture Space".children VALUES (21, \'missing\', 3)']

      error = run_error(runner, [parent(1, "a")], inserts: inserts) { raise "not reached" }

      expect([error.rule, error.sqlstate, error.step, error.index]).to eq([:insert_failed, "23503", :insert, 1])
      expect_nothing_persisted
    end

    it "rolls back and lets the block's own exception through untouched" do
      failure = Class.new(StandardError)

      expect do
        runner.with_fixture([parent(1, "a")]) do |tx|
          tx.query("SELECT 1")
          raise failure, "from the block"
        end
      end.to raise_error(failure, "from the block")
      expect_nothing_persisted
    end

    it "refuses a query that holds more than one statement" do
      error = run_error(runner, [parent(1, "a")]) do |tx|
        tx.query('SELECT 1; INSERT INTO "Fixture Space".counters DEFAULT VALUES')
      end

      expect([error.rule, error.sqlstate]).to eq([:query_failed, "42601"])
      expect_nothing_persisted
    end

    it "reports a statement that ended the transaction" do
      error = run_error { |tx| tx.query("COMMIT") }

      expect([error.rule, error.step, error.index]).to eq([:transaction_ended, :query, 0])
      expect(conn.transaction_status).to eq(0)
      # SET LOCAL ends with the transaction, even one that was committed.
      expect(conn.exec("SHOW statement_timeout").getvalue(0, 0)).to eq("0")
    end

    it "refuses a query through the transaction after the block has returned" do
      kept = nil
      runner.with_fixture { |tx| kept = tx }

      expect { kept.query('INSERT INTO "Fixture Space".counters DEFAULT VALUES') }
        .to raise_error(described_class::Error) { |e| expect(e.rule).to eq(:transaction_closed) }
      expect_nothing_persisted
    end

    it "turns a rollback that fails into its own error" do
      other = arena.connect

      error = run_error(described_class.new(other)) { other.close }

      expect([error.rule, error.sqlstate, error.step, error.cause]).to eq([:rollback_failed, nil, :rollback, nil])
    end
  end

  describe "a connection already inside a transaction" do
    it "refuses, and leaves that transaction alone" do
      conn.exec("BEGIN")
      conn.exec('INSERT INTO "Fixture Space".counters DEFAULT VALUES')
      yielded = false

      error = run_error { yielded = true }

      expect([error.rule, yielded]).to eq([:already_in_transaction, false])
      expect(conn.transaction_status).to eq(2)
      expect(conn.exec('SELECT count(*) FROM "Fixture Space".counters').getvalue(0, 0)).to eq("1")
      conn.exec("ROLLBACK")
    end
  end

  describe "fixture rows" do
    it "refuses a row whose columns and values don't line up, without naming the values" do
      expect { described_class::FixtureRow.new(table: parents, columns: %w[id note], values: [sentinel]) }
        .to raise_error(ArgumentError, "a fixture row needs one value per column")
    end

    it "refuses values that aren't Strings or nil, without naming them" do
      expect { described_class::FixtureRow.new(table: parents, columns: ["id"], values: [7]) }
        .to raise_error(ArgumentError, "fixture row values must be Strings or nil")
    end

    it "refuses a table that isn't a TableName, and column names that aren't non-empty Strings" do
      expect { described_class::FixtureRow.new(table: "public.t", columns: [], values: []) }
        .to raise_error(ArgumentError, "a fixture row's table must be a TableName")
      [[""], [:id]].each do |columns|
        expect { described_class::FixtureRow.new(table: parents, columns: columns, values: [nil]) }
          .to raise_error(ArgumentError, "fixture row columns must be non-empty Strings"), columns.inspect
      end
    end
  end

  # Postgres puts real values in its errors: a unique violation's DETAIL has
  # the key, and a check violation's has the whole row. None of it may reach
  # the runner's errors.
  describe "errors never carry values" do
    # Everything an error shows, down its cause chain.
    def texts_of(error)
      texts = []
      while error
        texts.push(error.message, error.full_message, error.detailed_message, error.inspect)
        %i[rule sqlstate step index].each { |field| texts << error.public_send(field).to_s if error.respond_to?(field) }
        error = error.cause
      end
      texts
    end

    # The same failure straight through the connection, to prove Postgres
    # really does put the sentinel in its error, so texts_of would find it.
    def raw_error(sql, params = [])
      other = arena.connect
      other.exec("BEGIN")
      other.exec_params(sql, params)
      raise "expected a database error"
    rescue StandardError => e
      e
    ensure
      other&.close
    end

    def expect_no_sentinel(error)
      expect(error).to be_a(described_class::Error)
      expect(error.cause).to be_nil
      expect(texts_of(error).grep(/#{sentinel}/)).to be_empty
    end

    def expect_sentinel_in_raw(sql, params = [])
      expect(texts_of(raw_error(sql, params)).grep(/#{sentinel}/)).not_to be_empty
    end

    it "keeps a colliding unique key out of the error" do
      error = run_error(runner, [parent(1, sentinel), parent(2, sentinel)])

      expect([error.rule, error.sqlstate]).to eq([:fixture_load_failed, "23505"])
      expect_no_sentinel(error)
      expect_sentinel_in_raw(<<~SQL, [sentinel])
        INSERT INTO "Fixture Space"."Parent Rows" (id, "Code") VALUES (1, $1), (2, $1)
      SQL
    end

    it "keeps a CHECK-violating row out of the error" do
      error = run_error(runner, [parent(1, "a", qty: -1, note: sentinel)])

      expect([error.rule, error.sqlstate]).to eq([:fixture_load_failed, "23514"])
      expect_no_sentinel(error)
      expect_sentinel_in_raw(<<~SQL, [sentinel])
        INSERT INTO "Fixture Space"."Parent Rows" (id, "Code", qty, note) VALUES (1, 'a', -1, $1)
      SQL
    end

    it "keeps a NOT NULL-violating row out of the error" do
      error = run_error(runner, [parent(1, nil, note: sentinel)])

      expect([error.rule, error.sqlstate]).to eq([:fixture_load_failed, "23502"])
      expect_no_sentinel(error)
      expect_sentinel_in_raw(<<~SQL, [sentinel])
        INSERT INTO "Fixture Space"."Parent Rows" (id, "Code", note) VALUES (1, NULL, $1)
      SQL
    end

    it "keeps a missing foreign key out of the error" do
      error = run_error(runner, [child(10, sentinel)])

      expect([error.rule, error.sqlstate]).to eq([:fixture_load_failed, "23503"])
      expect_no_sentinel(error)
      expect_sentinel_in_raw('INSERT INTO "Fixture Space".children (id, parent_code) VALUES (10, $1)', [sentinel])
    end

    it "keeps a raw INSERT statement's values out of the error" do
      sql = %(INSERT INTO "Fixture Space".children (id, parent_code) VALUES (10, '#{sentinel}'))

      error = run_error(runner, [], inserts: [sql])

      expect([error.rule, error.sqlstate]).to eq([:insert_failed, "23503"])
      expect_no_sentinel(error)
      expect_sentinel_in_raw(sql)
    end

    it "keeps a failing query's values and column names out of the error" do
      queries = [%(SELECT '#{sentinel}' AS "#{sentinel}", 1 / 0 AS "#{sentinel}-2"),
                 %(SELECT '#{sentinel}'::integer AS "#{sentinel}")]

      queries.each do |sql|
        error = run_error { |tx| tx.query(sql) }

        expect(error.rule).to eq(:query_failed)
        expect_no_sentinel(error)
      end
      expect_sentinel_in_raw(queries.last)
    end
  end
end
