-- A larger Rails-style schema, for rewrite-test's timing guard
-- (scenario_tests_timing_postgres_spec.rb): 19 tables, bigint identity keys,
-- unique indexes (one on an expression, one partial-free composite), foreign
-- keys, and CHECK constraints, the way an ORM app's migrations leave them.

CREATE TABLE public.accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  subdomain text NOT NULL,
  plan text NOT NULL CHECK (plan IN ('free', 'team', 'enterprise')),
  created_at timestamp(6) NOT NULL,
  updated_at timestamp(6) NOT NULL
);
CREATE UNIQUE INDEX index_accounts_on_subdomain ON public.accounts (subdomain);

CREATE TABLE public.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id bigint NOT NULL REFERENCES public.accounts (id),
  email character varying NOT NULL,
  name character varying,
  role character varying NOT NULL DEFAULT 'member',
  sign_in_count integer NOT NULL DEFAULT 0 CHECK (sign_in_count >= 0),
  encrypted_password character varying NOT NULL DEFAULT '',
  reset_password_token character varying,
  current_sign_in_at timestamp(6),
  last_sign_in_at timestamp(6),
  time_zone character varying NOT NULL DEFAULT 'UTC',
  locale character varying,
  confirmed_at timestamp(6),
  created_at timestamp(6) NOT NULL,
  updated_at timestamp(6) NOT NULL
);
CREATE UNIQUE INDEX index_users_on_lower_email ON public.users (lower((email)::text));
CREATE UNIQUE INDEX index_users_on_reset_password_token ON public.users (reset_password_token);
CREATE INDEX index_users_on_account_id ON public.users (account_id);

CREATE TABLE public.teams (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id bigint NOT NULL REFERENCES public.accounts (id),
  name character varying NOT NULL,
  created_at timestamp(6) NOT NULL,
  updated_at timestamp(6) NOT NULL
);
CREATE UNIQUE INDEX index_teams_on_account_id_and_name ON public.teams (account_id, name);

CREATE TABLE public.memberships (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id bigint NOT NULL REFERENCES public.teams (id),
  user_id bigint NOT NULL REFERENCES public.users (id),
  role text NOT NULL CHECK (role IN ('owner', 'admin', 'member')),
  created_at timestamp(6) NOT NULL,
  updated_at timestamp(6) NOT NULL
);
CREATE UNIQUE INDEX index_memberships_on_team_id_and_user_id ON public.memberships (team_id, user_id);
CREATE INDEX index_memberships_on_user_id ON public.memberships (user_id);

CREATE TABLE public.workflows (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id bigint NOT NULL REFERENCES public.accounts (id),
  name character varying NOT NULL,
  created_by_id bigint REFERENCES public.users (id),
  created_at timestamp(6) NOT NULL,
  updated_at timestamp(6) NOT NULL
);
CREATE UNIQUE INDEX index_workflows_on_account_id_and_name ON public.workflows (account_id, name);

CREATE TABLE public.projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id bigint NOT NULL REFERENCES public.accounts (id),
  team_id bigint REFERENCES public.teams (id),
  name character varying NOT NULL,
  slug character varying NOT NULL,
  archived boolean NOT NULL DEFAULT false,
  owner_id bigint REFERENCES public.users (id),
  default_workflow_id bigint REFERENCES public.workflows (id),
  description text,
  visibility text NOT NULL DEFAULT 'private' CHECK (visibility IN ('private', 'internal', 'public')),
  created_at timestamp(6) NOT NULL,
  updated_at timestamp(6) NOT NULL
);
CREATE UNIQUE INDEX index_projects_on_account_id_and_slug ON public.projects (account_id, slug);
CREATE INDEX index_projects_on_team_id ON public.projects (team_id);

CREATE TABLE public.milestones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint NOT NULL REFERENCES public.projects (id),
  title character varying NOT NULL,
  due_on date,
  created_at timestamp(6) NOT NULL,
  updated_at timestamp(6) NOT NULL
);

CREATE TABLE public.categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id bigint NOT NULL REFERENCES public.accounts (id),
  name character varying NOT NULL,
  position integer NOT NULL DEFAULT 0 CHECK (position >= 0),
  created_at timestamp(6) NOT NULL,
  updated_at timestamp(6) NOT NULL
);
CREATE UNIQUE INDEX index_categories_on_account_id_and_lower_name ON public.categories (account_id, lower((name)::text));

CREATE TABLE public.sprints (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint NOT NULL REFERENCES public.projects (id),
  number integer NOT NULL CHECK (number > 0),
  starts_on date NOT NULL,
  ends_on date NOT NULL,
  created_at timestamp(6) NOT NULL,
  updated_at timestamp(6) NOT NULL
);
CREATE UNIQUE INDEX index_sprints_on_project_id_and_number ON public.sprints (project_id, number);

CREATE TABLE public.tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint NOT NULL REFERENCES public.projects (id),
  milestone_id bigint REFERENCES public.milestones (id),
  assignee_id bigint REFERENCES public.users (id),
  creator_id bigint NOT NULL REFERENCES public.users (id),
  workflow_id bigint REFERENCES public.workflows (id),
  category_id bigint REFERENCES public.categories (id),
  sprint_id bigint REFERENCES public.sprints (id),
  external_ref character varying,
  description text,
  estimate_minutes integer CHECK (estimate_minutes >= 0),
  position integer NOT NULL DEFAULT 0,
  completed_at timestamp(6),
  title character varying NOT NULL,
  status text NOT NULL CHECK (status IN ('open', 'in_progress', 'done', 'closed')),
  priority integer NOT NULL DEFAULT 3 CHECK (priority BETWEEN 1 AND 5),
  due_at timestamp(6),
  created_at timestamp(6) NOT NULL,
  updated_at timestamp(6) NOT NULL
);
CREATE INDEX index_tasks_on_project_id ON public.tasks (project_id);
CREATE INDEX index_tasks_on_assignee_id ON public.tasks (assignee_id);

CREATE TABLE public.comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id bigint NOT NULL REFERENCES public.tasks (id),
  author_id bigint NOT NULL REFERENCES public.users (id),
  body text NOT NULL,
  created_at timestamp(6) NOT NULL,
  updated_at timestamp(6) NOT NULL
);
CREATE INDEX index_comments_on_task_id ON public.comments (task_id);

CREATE TABLE public.tags (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id bigint NOT NULL REFERENCES public.accounts (id),
  name character varying NOT NULL,
  created_at timestamp(6) NOT NULL,
  updated_at timestamp(6) NOT NULL
);
CREATE UNIQUE INDEX index_tags_on_account_id_and_name ON public.tags (account_id, name);

CREATE TABLE public.taggings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tag_id bigint NOT NULL REFERENCES public.tags (id),
  task_id bigint NOT NULL REFERENCES public.tasks (id),
  created_at timestamp(6) NOT NULL
);
CREATE UNIQUE INDEX index_taggings_on_tag_id_and_task_id ON public.taggings (tag_id, task_id);

CREATE TABLE public.attachments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id bigint NOT NULL REFERENCES public.tasks (id),
  uploader_id bigint NOT NULL REFERENCES public.users (id),
  filename character varying NOT NULL,
  byte_size bigint NOT NULL CHECK (byte_size >= 0),
  created_at timestamp(6) NOT NULL
);

CREATE TABLE public.invoices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id bigint NOT NULL REFERENCES public.accounts (id),
  number character varying NOT NULL,
  status text NOT NULL CHECK (status IN ('draft', 'open', 'paid', 'void')),
  total_cents integer NOT NULL CHECK (total_cents >= 0),
  issued_on date NOT NULL,
  created_at timestamp(6) NOT NULL,
  updated_at timestamp(6) NOT NULL
);
CREATE UNIQUE INDEX index_invoices_on_number ON public.invoices (number);

CREATE TABLE public.invoice_lines (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id bigint NOT NULL REFERENCES public.invoices (id),
  description character varying NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_cents integer NOT NULL
);

CREATE TABLE public.payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id bigint NOT NULL REFERENCES public.invoices (id),
  amount_cents integer NOT NULL CHECK (amount_cents > 0),
  paid_at timestamp(6) NOT NULL
);

CREATE TABLE public.api_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users (id),
  token_digest character varying NOT NULL,
  last_used_at timestamp(6),
  created_at timestamp(6) NOT NULL
);
CREATE UNIQUE INDEX index_api_tokens_on_token_digest ON public.api_tokens (token_digest);

CREATE TABLE public.audit_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id bigint NOT NULL REFERENCES public.accounts (id),
  actor_id bigint REFERENCES public.users (id),
  action character varying NOT NULL,
  created_at timestamp(6) NOT NULL
);
